# Challenge: processing a database

To facilitate the analysis of course registration data from a platform, you have been provided with a file named [`cursos_cadastrados.json`](https://cdn3.gnarususercontent.com.br/2929-pandas/cursos_cadastrados.json). You have been informed that this dataset may contain issues that could hinder accurate analysis and interpretation.

To address this, you are tasked with identifying and removing entries that exhibit the following problems:

- Null values: missing values ​​in certain columns that must be filled in to ensure an accurate analysis.
- Duplicates: identical records that could skew the analysis, as they represent the same information.
- Empty strings: text values ​​that contain no written content, which can complicate data analysis—especially if a column contains a large number of such entries.
- Data type conversion: some columns in the file may be in the wrong data format (e.g., text instead of numbers), which can interfere with analysis. In such cases, you must convert each column to its correct data type.


Given this context, you will need a systematic approach to clean the data. So, how can this be accomplished?

In [171]:
import pandas as pd
import numpy as np
import json

In [172]:
with open('/content/drive/MyDrive/Collab Notebooks - Alura/part_5_pandas_data_cleaning/exercises/resources/cursos_cadastrados.json', 'r') as f:
  data = json.load(f)
df = pd.json_normalize(data)
df

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
0,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999
1,Excel para iniciantes,Produtividade,None,None,None,None,None,None,Maria Oliveira,maria.oliveira@emailaleatorio.com,(11) 8888-8888
2,Marketing digital para negócios,Marketing,30 horas,75,2022-03-01,2022-03-31,Curso introdutório em marketing,89.9,Ana Santos,ana.santos@emailaleatorio.com,(11) 7777-7777
3,Inteligência artificial,Programação,40 horas,,2022-04-01,,Curso avançado sobre inteligência artificial c...,129.9,,contato@emailaleatorio.com,
4,Inglês para negócios,Idiomas,20 horas,30,,,Curso de inglês para negócios,69.9,John Smith,,
5,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999

1. Identifing and removing samples with null values

In [173]:
df.isnull()

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,True,True,True,True,True,True,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False

In [174]:
df.isnull().sum().sum()

np.int64(6)

In [175]:
df[df.isnull().any(axis=1)]

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
1,Excel para iniciantes,Produtividade,None,None,None,None,None,None,Maria Oliveira,maria.oliveira@emailaleatorio.com,(11) 8888-8888

In [176]:
df.dropna(inplace=True)

2. Identifing and removing samples with duplicate values

In [177]:
df.duplicated().sum()

np.int64(1)

In [178]:
df[df.duplicated()]

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
5,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999

In [179]:
df.drop_duplicates(inplace=True)

In [180]:
df.duplicated().sum()

np.int64(0)

3. Removing samples with empty strings

In [181]:

df[(df == '').any(axis=1)]

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
3,Inteligência artificial,Programação,40 horas,,2022-04-01,,Curso avançado sobre inteligência artificial c...,129.9,,contato@emailaleatorio.com,
4,Inglês para negócios,Idiomas,20 horas,30,,,Curso de inglês para negócios,69.9,John Smith,,

In [182]:
df.replace('', pd.NA, inplace=True)
df[df.isnull().any(axis=1)]

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
3,Inteligência artificial,Programação,40 horas,<NA>,2022-04-01,<NA>,Curso avançado sobre inteligência artificial c...,129.9,<NA>,contato@emailaleatorio.com,<NA>
4,Inglês para negócios,Idiomas,20 horas,30,<NA>,<NA>,Curso de inglês para negócios,69.9,John Smith,<NA>,<NA>

In [183]:
df.dropna(inplace=True)

In [184]:
df.isnull().sum().sum()

np.int64(0)

In [185]:
df[(df == '').any(axis=1)].sum().sum()

0

In [186]:
df.reset_index(drop=True, inplace=True)

In [187]:
df

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
0,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999
1,Marketing digital para negócios,Marketing,30 horas,75,2022-03-01,2022-03-31,Curso introdutório em marketing,89.9,Ana Santos,ana.santos@emailaleatorio.com,(11) 7777-7777

In [188]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   curso               2 non-null      object
 1   categoria           2 non-null      object
 2   carga_horaria       2 non-null      object
 3   concluintes         2 non-null      object
 4   data_inicio         2 non-null      object
 5   data_conclusao      2 non-null      object
 6   descricao           2 non-null      object
 7   preco               2 non-null      object
 8   instrutor.nome      2 non-null      object
 9   instrutor.email     2 non-null      object
 10  instrutor.telefone  2 non-null      object
dtypes: object(11)
memory usage: 308.0+ bytes

In [189]:
df['concluintes'] = df['concluintes'].astype(np.int64)

In [190]:
df['data_inicio'] = pd.to_datetime(df['data_inicio'])

In [191]:
df['data_conclusao'] = pd.to_datetime(df['data_conclusao'])

In [192]:
df['preco'] = df['preco'].astype(np.float64)

In [193]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   curso               2 non-null      object
 1   categoria           2 non-null      object
 2   carga_horaria       2 non-null      object
 3   concluintes         2 non-null      int64
 4   data_inicio         2 non-null      datetime64[ns]
 5   data_conclusao      2 non-null      datetime64[ns]
 6   descricao           2 non-null      object
 7   preco               2 non-null      float64
 8   instrutor.nome      2 non-null      object
 9   instrutor.email     2 non-null      object
 10  instrutor.telefone  2 non-null      object
dtypes: datetime64[ns](2), float64(1), int64(1), object(7)
memory usage: 308.0+ bytes