# Challenge: processing the data

You received and downloaded a JSON file named “[dados.json](https://cdn3.gnarususercontent.com.br/2929-pandas/dados.json)” that contains the following:

Your task is to perform some data processing to convert this JSON file into a Pandas DataFrame, ensuring there are no empty values ​​and that the columns have the correct data types. How can this be done?

In [86]:
import pandas as pd

In [87]:
data = pd.read_json('/content/drive/MyDrive/Collab Notebooks - Alura/part_5_pandas_data_cleaning/exercises/resources/dados.json')
data

                                             pessoas
0  {'nome': 'João', 'idade': '25', 'endereco': {'...
1  {'nome': 'Maria', 'idade': 30, 'endereco': {'r...

In [88]:
import json
with open('/content/drive/MyDrive/Collab Notebooks - Alura/part_5_pandas_data_cleaning/exercises/resources/dados.json', 'r') as f:
  raw_json = json.load(f)
raw_json

{'pessoas': [{'nome': 'João',
   'idade': '25',
   'endereco': {'rua': 'Rua A', 'numero': 123, 'cidade': 'São Paulo'},
   'telefones': ['11 1111-1111', '11 2222-2222']},
  {'nome': 'Maria',
   'idade': 30,
   'endereco': {'rua': '', 'numero': 456, 'cidade': 'Rio de Janeiro'},
   'telefones': ['21 3333-3333']}]}

In [89]:
data = pd.json_normalize(raw_json, record_path='pessoas')
data

,nome,idade,telefones,endereco.rua,endereco.numero,endereco.cidade
0,João,25,"[11 1111-1111, 11 2222-2222]",Rua A,123,São Paulo
1,Maria,30,[21 3333-3333],,456,Rio de Janeiro

In [90]:
data = data.explode("telefones")
data.reset_index(inplace=True, drop=True)
data

    nome idade     telefones endereco.rua  endereco.numero endereco.cidade
0   João    25  11 1111-1111        Rua A              123       São Paulo
1   João    25  11 2222-2222        Rua A              123       São Paulo
2  Maria    30  21 3333-3333                           456  Rio de Janeiro

In [91]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   nome             3 non-null      object
 1   idade            3 non-null      object
 2   telefones        3 non-null      object
 3   endereco.rua     3 non-null      object
 4   endereco.numero  3 non-null      int64
 5   endereco.cidade  3 non-null      object
dtypes: int64(1), object(5)
memory usage: 276.0+ bytes

In [92]:
data['idade'] = data['idade'].astype(int)

In [93]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   nome             3 non-null      object
 1   idade            3 non-null      int64
 2   telefones        3 non-null      object
 3   endereco.rua     3 non-null      object
 4   endereco.numero  3 non-null      int64
 5   endereco.cidade  3 non-null      object
dtypes: int64(2), object(4)
memory usage: 276.0+ bytes

First option

In [97]:
data[data['endereco.rua'] != '']

   nome  idade     telefones endereco.rua  endereco.numero endereco.cidade
0  João     25  11 1111-1111        Rua A              123       São Paulo
1  João     25  11 2222-2222        Rua A              123       São Paulo

Second option

In [100]:
data.query('`endereco.rua` != ""')

   nome  idade     telefones endereco.rua  endereco.numero endereco.cidade
0  João     25  11 1111-1111        Rua A              123       São Paulo
1  João     25  11 2222-2222        Rua A              123       São Paulo