# Transforming date data

To continue the work toward implementing intelligent pricing. We going to work with a new set of data, also a json file:
- [moveis_disponiveis.json](https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/moveis_disponiveis.json://)

In [26]:
import pandas as pd

In [27]:
dt_data = pd.read_json('/content/drive/MyDrive/Collab Notebooks - Alura/part_4_pandas_data_transformation/resources/moveis_disponiveis.json')
dt_data.head()

    id        data  vaga_disponivel preco
0  857  2016-01-04            False  None
1  857  2016-01-05            False  None
2  857  2016-01-06            False  None
3  857  2016-01-07            False  None
4  857  2016-01-08            False  None

In [28]:
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  object
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  object
dtypes: bool(1), int64(1), object(2)
memory usage: 11.5+ MB

### Converting `string` type data to `datetime`.

In [29]:
dt_data['data'] = pd.to_datetime(dt_data['data'])
dt_data['data']

0        2016-01-04
1        2016-01-05
2        2016-01-06
3        2016-01-07
4        2016-01-08
            ...
364995   2016-12-29
364996   2016-12-30
364997   2016-12-31
364998   2017-01-01
364999   2017-01-02
Name: data, Length: 365000, dtype: datetime64[ns]

In [30]:
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  datetime64[ns]
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(1), object(1)
memory usage: 11.5+ MB

# Date manipulation

Now, let’s focus on manipulating our time-related data to build a dataset of real estate offerings available for rent throughout 2016.

In [31]:
dt_data.head()

    id       data  vaga_disponivel preco
0  857 2016-01-04            False  None
1  857 2016-01-05            False  None
2  857 2016-01-06            False  None
3  857 2016-01-07            False  None
4  857 2016-01-08            False  None

In [32]:
dt_data['data'].dt.strftime('%Y-%m')

0         2016-01
1         2016-01
2         2016-01
3         2016-01
4         2016-01
           ...
364995    2016-12
364996    2016-12
364997    2016-12
364998    2017-01
364999    2017-01
Name: data, Length: 365000, dtype: object

In [34]:
subset = dt_data.groupby(dt_data['data'].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()
subset

data
2016-01    16543
2016-02    20128
2016-03    23357
2016-04    22597
2016-05    23842
2016-06    23651
2016-07    22329
2016-08    22529
2016-09    22471
2016-10    23765
2016-11    23352
2016-12    24409
2017-01     1574
Name: vaga_disponivel, dtype: int64

In [ ]:
dt_data.to_json('moveis_disponiveis_v2', index=False)