# Challenge: manipulating a database

It is time to test the knowledge you gained during the lesson.

You are tasked with creating a local database of customers for a financial institution. You have a [CSV file](https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv) containing the customer data.

Your mission is:

1. Create a local database using the SQLAlchemy library.
2. Write the data from the CSV file into this local database.
3. Perform three updates to the database:
    - Update the record for the client with ID 6840104, whose annual income has changed to 300,000.
    - Delete the record for the client with ID 5008809, as this individual no longer holds an account with the financial institution.
    - Create a new client record according to the following specifications:
        - Client_ID: 6850985
        - Age: 33
        - Education_level: Doctorate
        - Marital_status: Single
        - Family_size: 1
        - Income_category: Employed
        - Occupation: IT
        - Years_employed: 2
        - Annual_income: 290,000
        Has_car: 0
        - Housing: Owns home/apartment

In [13]:
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine, inspect, text

### Creating local data base

In [7]:
engine = create_engine('sqlite:///:memory:')

### Reading the csv file and writing the data into the databas as a table

In [8]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'

In [10]:
client_data = pd.read_csv(url)

In [11]:
client_data.to_sql('clients', engine, index=False)

438463

### Inspecting to ensure table was created successfully

In [12]:
inspector = inspect(engine)
print(inspector.get_table_names())

['clients']

In [19]:
pd.read_sql_table('clients', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438459,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438460,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438461,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438462,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

### Performing updates to the database

Task:
- Update the record for the client with ID 6840104, whose annual income has changed to 300,000.

In [20]:
query = 'SELECT * FROM clients WHERE ID_Cliente = 6840104'
pd.read_sql_query(query, engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio

In [22]:
query = 'UPDATE clients SET Rendimento_anual = 300000.00 WHERE ID_Cliente=6840104'

with engine.connect() as conn:
  conn.execute(text(query))
  conn.commit()

In [23]:
query = 'SELECT * FROM clients WHERE ID_Cliente = 6840104'
pd.read_sql_query(query, engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,300000.0,0,Casa/apartamento próprio

Task:
- Delete the record for the client with ID 5008809, as this individual no longer holds an account with the financial institution.

In [25]:
query = 'SELECT * FROM clients WHERE ID_Cliente=5008809'
pd.read_sql_query(query, engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio

In [26]:
query = 'DELETE FROM clients WHERE ID_Cliente = 5008809'
with engine.connect() as conn:
  conn.execute(text(query))
  conn.commit()

In [27]:
query = 'SELECT * FROM clients WHERE ID_Cliente=5008809'
pd.read_sql_query(query, engine)

Empty DataFrame
Columns: [ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia]
Index: []

Task:
- Create a new client record according to the following specifications:
    - Client_ID: 6850985
    - Age: 33
    - Education_level: Doctorate
    - Marital_status: Single
    - Family_size: 1
    - Income_category: Employed
    - Occupation - IT
    - Years_employed: 2
    - Annual_income: 290,000
    - Has_car: 0
    - Housing: Owns home/apartment

In [29]:
query = """
INSERT INTO clients (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, \
Categoria_de_renda,	Ocupacao,	Anos_empregado,	Rendimento_anual,	Tem_carro,	Moradia)
VALUES
('6850985', 33, 'Dotourado', 'Solteiro', 1, 'Empregado', 'TI', 2, 290000.00, 0, 'Casa/apartamento próprio')
"""

with engine.connect() as conn:
  conn.execute(text(query))
  conn.commit()

In [30]:
query = 'SELECT * FROM clients WHERE ID_Cliente =6850985'
pd.read_sql_query(query, engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,6850985,33,Dotourado,Solteiro,1,Empregado,TI,2,290000.0,0,Casa/apartamento próprio

In [31]:
pd.read_sql_table('clients', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio
438462,6850985,33,Dotourado,Solteiro,1,Empregado,TI,2,290000.0,0,Casa/apartamento próprio