## Challenge

Import the file [**alunos.csv**](https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv) again to complete the challenges below.

In [ ]:
import pandas as pd
url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv'

In [ ]:
data = pd.read_csv(url)
data.head()

    Nome  Idade  Notas  Aprovado
0    Ary     20    7.5      True
1    Ana     18    NaN     False
2  Cátia     27    2.5     False
3  Denis     18    5.0     False
4   Beto     21   10.0      True

### Challenge 1
Check whether the dataset contains null values ​​and, if so, handle these null values.

In [ ]:
data.isnull().sum()

Nome        0
Idade       0
Notas       6
Aprovado    0
dtype: int64

In [ ]:
data = data.fillna(0)

In [ ]:
data.isnull().sum()

Nome        0
Idade       0
Notas       0
Aprovado    0
dtype: int64

### Challenge 2
The students "Alice" and "Carlos" are no longer part of the class. Therefore, remove them from the database.

In [ ]:
students_to_remove = data.query('Nome == "Alice" or Nome == "Carlos"').index
students_to_remove

Index([7, 8], dtype='int64')

In [ ]:
data.drop(students_to_remove, axis=0, inplace=True)

In [ ]:
data

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    0.0     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    0.0     False
6        Dara     21    7.0      True
9       Vitor     28    0.0     False
10     Daniel     21    0.0     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    0.0     False
15     Mylena     29    7.0      True
16      Lucas     33    0.0     False
17      Nadia     34    8.0      True

### Challenge 3
Apply a filter that selects only the students who passed

**One way to do it**

In [ ]:
data = data.query('Aprovado == True')

**Second way of doing it**

In [ ]:
selection = data['Aprovado'] == True
data[selection]

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
4        Beto     21   10.0      True
6        Dara     21    7.0      True
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
15     Mylena     29    7.0      True
17      Nadia     34    8.0      True

### Challenge 4
Save the DataFrame containing only the students who passed to a CSV file named "alunos_aprovados.csv"

In [ ]:
approved_students = data[selection]

In [ ]:
approved_students.to_csv('students_approved.csv', index=False)

In [ ]:
pd.read_csv('students_approved.csv')

        Nome  Idade  Notas  Aprovado
0        Ary     20    7.5      True
1       Beto     21   10.0      True
2       Dara     21    7.0      True
3  Sthefanie     26    9.5      True
4      Mirla     25    9.0      True
5     Mylena     29    7.0      True
6      Nadia     34    8.0      True

### **Extra**
Upon reviewing the grades of the students who passed, we noticed that some scores were incorrect. The students who received a 7.0 actually had an extra point that was not accounted for. Therefore, replace the 7.0 grades in the dataset with 8.0. **Tip**: look into the **replace** method.

In [ ]:
approved_students.replace(7.0, 8.0)

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
4        Beto     21   10.0      True
6        Dara     21    8.0      True
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
15     Mylena     29    8.0      True
17      Nadia     34    8.0      True

In [ ]:
approved_students = approved_students.replace(7.0, 8.0)

In [ ]:
approved_students

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
4        Beto     21   10.0      True
6        Dara     21    8.0      True
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
15     Mylena     29    8.0      True
17      Nadia     34    8.0      True

In [ ]:
approved_students.to_csv('students_approved.csv', index=False)