# Challenge: Student Dataset
*Dataset: [alunos.csv](https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv)*
### Exercises

1) Import the `alunos.csv` file and store its content in a Pandas DataFrame.

2) Display the first 7 rows and the last 5 rows of the DataFrame.

3) Check the number of rows and columns in this DataFrame.

4) Explore the DataFrame's columns and analyze the data types present in each column.

Extra: Calculate some basic descriptive statistics for the data in the DataFrame (mean, standard deviation, etc.). Tip: look up the `describe` method.

In [1]:
import pandas as pd

In [2]:
url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv'

pd.read_csv(url)

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    NaN     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    NaN     False
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
8       Alice     35    5.6     False
9       Vitor     28    NaN     False
10     Daniel     21    NaN     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    NaN     False
15     Mylena     29    7.0      True
16      Lucas     33    NaN     False
17      Nadia     34    8.0      True

In [3]:
students_data = pd.read_csv(url)

In [4]:
students_data.head(7)

    Nome  Idade  Notas  Aprovado
0    Ary     20    7.5      True
1    Ana     18    NaN     False
2  Cátia     27    2.5     False
3  Denis     18    5.0     False
4   Beto     21   10.0      True
5  Bruna     23    NaN     False
6   Dara     21    7.0      True

In [5]:
students_data.tail(5)

      Nome  Idade  Notas  Aprovado
13   Mirla     25    9.0      True
14   Paulo     37    NaN     False
15  Mylena     29    7.0      True
16   Lucas     33    NaN     False
17   Nadia     34    8.0      True

In [7]:
students_data.shape

print(f'Rows: {students_data.shape[0]}\nColumns: {students_data.shape[1]}')

Rows: 18
Columns: 4

In [8]:
students_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nome      18 non-null     object
 1   Idade     18 non-null     int64
 2   Notas     12 non-null     float64
 3   Aprovado  18 non-null     bool
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 582.0+ bytes

In [9]:
students_data.dtypes

Nome         object
Idade         int64
Notas       float64
Aprovado       bool
dtype: object

In [10]:
students_data.columns

Index(['Nome', 'Idade', 'Notas', 'Aprovado'], dtype='object')

In [11]:
students_data[['Nome', 'Idade', 'Notas']]

         Nome  Idade  Notas
0         Ary     20    7.5
1         Ana     18    NaN
2       Cátia     27    2.5
3       Denis     18    5.0
4        Beto     21   10.0
5       Bruna     23    NaN
6        Dara     21    7.0
7      Carlos     19    6.0
8       Alice     35    5.6
9       Vitor     28    NaN
10     Daniel     21    NaN
11       Igor     24    4.5
12  Sthefanie     26    9.5
13      Mirla     25    9.0
14      Paulo     37    NaN
15     Mylena     29    7.0
16      Lucas     33    NaN
17      Nadia     34    8.0

In [12]:
students_data['Aprovado']

0      True
1     False
2     False
3     False
4      True
5     False
6      True
7      True
8     False
9     False
10    False
11    False
12     True
13     True
14    False
15     True
16    False
17     True
Name: Aprovado, dtype: bool

In [13]:
students_data.describe()

           Idade      Notas
count  18.000000  12.000000
mean   25.500000   6.800000
std     6.070662   2.204953
min    18.000000   2.500000
25%    21.000000   5.450000
50%    24.500000   7.000000
75%    28.750000   8.250000
max    37.000000  10.000000