## Challenge

Import the file [**alunos.csv**](https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv) again to complete the challenges below.

In [2]:
# Importando novamente os dados
import pandas as pd

url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv'

data = pd.read_csv(url)
data

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    NaN     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    NaN     False
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
8       Alice     35    5.6     False
9       Vitor     28    NaN     False
10     Daniel     21    NaN     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    NaN     False
15     Mylena     29    7.0      True
16      Lucas     33    NaN     False
17      Nadia     34    8.0      True

### Challenge 1
Students participated in an extracurricular activity and earned extra points. These extra points correspond to 40% of each student's current grade. Based on this, create a column named "Pontos_extras" (Extra_points) that contains the extra points for each student—that is, 40% of their current grade.

In [3]:
percentage = 40 / 100

data['Pontos_extras'] = data['Notas'].apply(lambda x: x * percentage)
data

         Nome  Idade  Notas  Aprovado  Pontos_extras
0         Ary     20    7.5      True           3.00
1         Ana     18    NaN     False            NaN
2       Cátia     27    2.5     False           1.00
3       Denis     18    5.0     False           2.00
4        Beto     21   10.0      True           4.00
5       Bruna     23    NaN     False            NaN
6        Dara     21    7.0      True           2.80
7      Carlos     19    6.0      True           2.40
8       Alice     35    5.6     False           2.24
9       Vitor     28    NaN     False            NaN
10     Daniel     21    NaN     False            NaN
11       Igor     24    4.5     False           1.80
12  Sthefanie     26    9.5      True           3.80
13      Mirla     25    9.0      True           3.60
14      Paulo     37    NaN     False            NaN
15     Mylena     29    7.0      True           2.80
16      Lucas     33    NaN     False            NaN
17      Nadia     34    8.0      True           3.20

### Challenge 2
Create an additional column named "Final_grades" that contains each student's grades with the extra points added.

In [4]:
data['Final_grades'] = data['Notas'] + data['Pontos_extras']
data

         Nome  Idade  Notas  Aprovado  Pontos_extras  Final_grades
0         Ary     20    7.5      True           3.00         10.50
1         Ana     18    NaN     False            NaN           NaN
2       Cátia     27    2.5     False           1.00          3.50
3       Denis     18    5.0     False           2.00          7.00
4        Beto     21   10.0      True           4.00         14.00
5       Bruna     23    NaN     False            NaN           NaN
6        Dara     21    7.0      True           2.80          9.80
7      Carlos     19    6.0      True           2.40          8.40
8       Alice     35    5.6     False           2.24          7.84
9       Vitor     28    NaN     False            NaN           NaN
10     Daniel     21    NaN     False            NaN           NaN
11       Igor     24    4.5     False           1.80          6.30
12  Sthefanie     26    9.5      True           3.80         13.30
13      Mirla     25    9.0      True           3.60         12.60
14      Paulo     37    NaN     False            NaN           NaN
15     Mylena     29    7.0      True           2.80          9.80
16      Lucas     33    NaN     False            NaN           NaN
17      Nadia     34    8.0      True           3.20         11.20

### Challenge 3
Since the students received extra points, some who had not previously passed may now have passed. Based on this, create a column named "Aprovado_final" with the following values:

* True: if the student has passed (final grade must be greater than or equal to 6);
* False: if the student has failed (final grade must be less than 6).

In [7]:
data['Aprovado_final'] = data['Final_grades'].apply(lambda x: True if x >= 6 else False)
data

,Nome,Idade,Notas,Aprovado,Pontos_extras,Final_grades,Aprovado_final
0,Ary,20,7.5,True,3.00,10.50,True
1,Ana,18,NaN,False,NaN,NaN,False
2,Cátia,27,2.5,False,1.00,3.50,False
3,Denis,18,5.0,False,2.00,7.00,True
4,Beto,21,10.0,True,4.00,14.00,True
5,Bruna,23,NaN,False,NaN,NaN,False
6,Dara,21,7.0,True,2.80,9.80,True
7,Carlos,19,6.0,True,2.40,8.40,True
8,Alice,35,5.6,False,2.24,7.84,True
9,Vitor,28,NaN,False,NaN,NaN,False
10,Daniel,21,NaN,False,NaN,NaN,False
11,Igor,24,4.5,False,1.80,6.30,True
12,Sthefanie,26,9.5,True,3.80,13.30,True
13,Mirla,25,9.0,True,3.60,12.60,True
14,Paulo,37,NaN,False,NaN,NaN,False
15,Mylena,29,7.0,True,2.80,9.80,True
16,Lucas,33,NaN,False,NaN,NaN,False
17,Nadia,34,8.0,True,3.20,11.20,True

### Challenge 4
Identify which students had not previously passed but did pass after the addition of extra points.

In [8]:
data.query('Aprovado == False & Aprovado_final == True')

     Nome  Idade  Notas  Aprovado  Pontos_extras  Final_grades  Aprovado_final
3   Denis     18    5.0     False           2.00          7.00            True
8   Alice     35    5.6     False           2.24          7.84            True
11   Igor     24    4.5     False           1.80          6.30            True

In [9]:
selection = (data['Aprovado'] == False) & (data['Aprovado_final'] == True)
data[selection]

     Nome  Idade  Notas  Aprovado  Pontos_extras  Final_grades  Aprovado_final
3   Denis     18    5.0     False           2.00          7.00            True
8   Alice     35    5.6     False           2.24          7.84            True
11   Igor     24    4.5     False           1.80          6.30            True