# Challenge: working in other contexts

It’s time to put everything we’ve learned during the lessons into practice. I’ve prepared two extra projects for us to work on throughout the course, ensuring plenty of opportunities for practice! For these, we’ll be using two new datasets—though, this time, they will be much smaller. You can download the datasets below:

- Challenge Project 1: Online Sales – [dados_vendas_clientes.json](https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_vendas_clientes.json)
- Challenge Project 2: Property/Condominium Management – [​​dados_locacao_imoveis.json](https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_locacao_imoveis.json)

In each lesson, we will develop one stage of the projects. Therefore, save the code you build for each challenge so that you can apply it in subsequent challenges.

## STAGE 1

### - Challenge Project 1: Online Sales



The objective of this project is to analyze the results of an event involving customers of an online retail company. A dataset has been collected, containing information on the customers who spent the most on products during a 5-day sales event. This analysis will identify the customer who made the largest purchase during the week—who will then receive a prize from the store—and will also help the company develop new strategies to attract more customers.

The dataset used for this analysis is `dados_vendas_clientes.json`, which contains key information about the customers, such as their registered name, the total amount paid for their purchase, and the date of the purchase.

Given this information, the task for Challenge Project 1 (Online Sales) is to open the dataset using Pandas and apply `json_normalize`.

In [396]:
import pandas as pd

In [397]:
sales_data = pd.read_json('/content/drive/MyDrive/Collab Notebooks - Alura/part_4_pandas_data_transformation/exercises/resources/dados_vendas_clientes.json')
sales_data.head()

                                        dados_vendas
0  {'Data de venda': '06/06/2022', 'Cliente': ['@...
1  {'Data de venda': '07/06/2022', 'Cliente': ['I...
2  {'Data de venda': '08/06/2022', 'Cliente': ['I...
3  {'Data de venda': '09/06/2022', 'Cliente': ['J...
4  {'Data de venda': '10/06/2022', 'Cliente': ['M...

In [398]:
sales_data = pd.json_normalize(sales_data['dados_vendas'])
sales_data.head()

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

### - Challenge Project 2: Condominium Management


Managing a condominium is a task that requires a great deal of attention and organization. Among the various management responsibilities is the collection of rent from tenants. To ensure the financial health of the property, it is essential that these payments are made regularly and on time. However, we know that this does not always happen.

With this in mind, I am proposing a data-processing challenge aimed at analyzing late rent payments by some residents in a condominium. I have provided the dataset `dados_locacao_imoveis.json`, which contains information regarding the tenants' apartments, the agreed-upon rent due date, the actual date the rent was paid, and the rent amount.

Given this information, the challenge for Project 2 (Condominium Management) will be similar to the challenge in Project 1: load the dataset using Pandas and apply `json_normalize` to the DataFrame.

In [399]:
condominium_data = pd.read_json('/content/drive/MyDrive/Collab Notebooks - Alura/part_4_pandas_data_transformation/exercises/resources/dados_locacao_imoveis.json')
condominium_data.head()

                                       dados_locacao
0  {'apartamento': 'A101 (blocoAP)', 'datas_combi...
1  {'apartamento': 'A102 (blocoAP)', 'datas_combi...
2  {'apartamento': 'B201 (blocoAP)', 'datas_combi...
3  {'apartamento': 'B202 (blocoAP)', 'datas_combi...
4  {'apartamento': 'C301 (blocoAP)', 'datas_combi...

In [400]:
condominium_data = pd.json_normalize(condominium_data['dados_locacao'])
condominium_data.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"

## STAGE 2

### - Challenge Project 1: Online Sales

We read the dataset in the previous challenge; now, we can move on to transforming this data. Therefore, the new challenge for Project 1 will be broken down into a few goals:

- Remove data stored in lists within the DataFrame;
- Check the data types;
- Identify numerical columns;
- Convert the numerical columns to a numeric data type.

In [401]:
columns_list = list(sales_data.columns)
columns_list

['Data de venda', 'Cliente', 'Valor da compra']

In [402]:
sales_data = sales_data.explode(columns_list[1:])
sales_data.reset_index(inplace=True, drop=True)
sales_data.head()

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
1    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4    07/06/2022  Isabely JOanes 738       R$ 825,31

In [403]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [404]:
sales_data['Valor da compra']

0      R$ 836,5
1     R$ 573,33
2      R$ 392,8
3     R$ 512,34
4     R$ 825,31
5     R$ 168,07
6     R$ 339,18
7     R$ 314,69
8     R$ 682,05
9     R$ 386,34
10    R$ 622,65
11    R$ 630,79
12     R$ 390,3
13    R$ 759,16
14    R$ 334,47
15    R$ 678,78
16    R$ 314,24
17    R$ 311,15
18    R$ 899,16
19    R$ 885,24
Name: Valor da compra, dtype: object

In [405]:
sales_data['Valor da compra'] = sales_data['Valor da compra'].apply(lambda x: x.replace('R$ ', '').replace(',', '.').strip())

In [406]:
import numpy as np

In [407]:
sales_data['Valor da compra'] = sales_data['Valor da compra'].astype(np.float64)

In [408]:
sales_data['Valor da compra']

0     836.50
1     573.33
2     392.80
3     512.34
4     825.31
5     168.07
6     339.18
7     314.69
8     682.05
9     386.34
10    622.65
11    630.79
12    390.30
13    759.16
14    334.47
15    678.78
16    314.24
17    311.15
18    899.16
19    885.24
Name: Valor da compra, dtype: float64

In [409]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 612.0+ bytes

### - Challenge Project 2: Condominium Management

Having read the dataset in the previous challenge, we can now move on to transforming this data. As with Project 1, the challenge for Project 2 is broken down into a few specific goals:

- Remove data contained in lists within the DataFrame;
- Check the data types;
- Identify numerical columns;
- Convert the numerical columns to a numeric data type.

In [410]:
columns_list = list(condominium_data.columns)
columns_list

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [411]:
condominium_data = condominium_data.explode(columns_list[1:])
condominium_data.reset_index(inplace=True, drop=True)
condominium_data

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
3,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
4,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
5,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
6,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
7,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
8,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
9,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
10,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
11,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
12,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
13,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
14,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
15,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
16,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
17,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
18,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
19,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
20,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
21,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
22,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
23,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
24,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
25,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
26,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
27,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
28,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
29,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [412]:
condominium_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB

In [413]:
condominium_data['valor_aluguel']

0     $ 1000,0 reais
1     $ 2500,0 reais
2     $ 1100,0 reais
3     $ 2600,0 reais
4     $ 1200,0 reais
5     $ 2700,0 reais
6     $ 1300,0 reais
7     $ 2800,0 reais
8     $ 1400,0 reais
9     $ 2900,0 reais
10    $ 1500,0 reais
11    $ 1200,0 reais
12    $ 1600,0 reais
13    $ 1300,0 reais
14    $ 1700,0 reais
15    $ 1400,0 reais
16    $ 1800,0 reais
17    $ 1500,0 reais
18    $ 1900,0 reais
19    $ 1600,0 reais
20    $ 2000,0 reais
21    $ 1000,0 reais
22    $ 2100,0 reais
23    $ 1100,0 reais
24    $ 2200,0 reais
25    $ 1200,0 reais
26    $ 2300,0 reais
27    $ 2100,0 reais
28    $ 2400,0 reais
29    $ 2200,0 reais
Name: valor_aluguel, dtype: object

In [414]:
condominium_data['valor_aluguel'] = condominium_data['valor_aluguel'].apply(lambda x: x.replace('$ ', '').replace(',', '.').replace(' reais', '').strip())

In [415]:
condominium_data['valor_aluguel'] =  condominium_data['valor_aluguel'].astype(np.float64)

In [416]:
condominium_data['valor_aluguel']

0     1000.0
1     2500.0
2     1100.0
3     2600.0
4     1200.0
5     2700.0
6     1300.0
7     2800.0
8     1400.0
9     2900.0
10    1500.0
11    1200.0
12    1600.0
13    1300.0
14    1700.0
15    1400.0
16    1800.0
17    1500.0
18    1900.0
19    1600.0
20    2000.0
21    1000.0
22    2100.0
23    1100.0
24    2200.0
25    1200.0
26    2300.0
27    2100.0
28    2400.0
29    2200.0
Name: valor_aluguel, dtype: float64

In [417]:
condominium_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

## STAGE 3

### - Challenge Project 1: Online Sales

In stage 2, we worked on transforming numerical data. Now, we can address textual values.

Due to an instability on the company's website, issues arose with customer names during the saving process. This resulted in a `"Cliente"` (costumer) column containing a mix of uppercase and lowercase letters, numbers, and other characters.

Given this, manipulate the text in the `"Cliente"` (costumer) column so that the final output consists of customer names in all lowercase letters, with all special characters and numbers removed.

In [418]:
sales_data['Cliente']

0        @ANA _LUCIA 321
1     DieGO ARMANDIU 210
2     DieGO ARMANDIU 210
3     DieGO ARMANDIU 210
4     Isabely JOanes 738
5     Isabely JOanes 738
6     Isabely JOanes 738
7     Isabely JOanes 738
8     Isabely JOanes 738
9       JOãO Gabriel 671
10    Julya meireles 914
11    Julya meireles 914
12    Julya meireles 914
13       MaRIA Julia 444
14       MaRIA Julia 444
15       MaRIA Julia 444
16       MaRIA Julia 444
17       PEDRO PASCO 812
18      Paulo castro 481
19     Thiago fritzz 883
Name: Cliente, dtype: object

In [419]:
sales_data['Cliente'] = sales_data['Cliente'].str.lower()

In [420]:
sales_data.head(3)

  Data de venda             Cliente  Valor da compra
0    06/06/2022     @ana _lucia 321           836.50
1    06/06/2022  diego armandiu 210           573.33
2    06/06/2022  diego armandiu 210           392.80

In [421]:
sales_data['Cliente'] = sales_data['Cliente'].str.replace('[^a-z ]', '', regex=True)
sales_data['Cliente']

0          ana lucia
1     diego armandiu
2     diego armandiu
3     diego armandiu
4     isabely joanes
5     isabely joanes
6     isabely joanes
7     isabely joanes
8     isabely joanes
9        joo gabriel
10    julya meireles
11    julya meireles
12    julya meireles
13       maria julia
14       maria julia
15       maria julia
16       maria julia
17       pedro pasco
18      paulo castro
19     thiago fritzz
Name: Cliente, dtype: object

In [422]:
sales_data.head()

  Data de venda          Cliente  Valor da compra
0    06/06/2022       ana lucia            836.50
1    06/06/2022  diego armandiu            573.33
2    06/06/2022  diego armandiu            392.80
3    06/06/2022  diego armandiu            512.34
4    07/06/2022  isabely joanes            825.31

### - Challenge Project 2: Condominium Management

In stage 2, we worked on transforming numerical data. Now, we can address textual values.

To clarify how the apartment identifiers are organized, the string "(blocoAP)" was included when the dataset was created. This indicates that the apartment names are structured as the block letter followed by the apartment number. However, this does not provide any useful information for our data, so it is advisable to remove this text from the dataset.

Accordingly, manipulate the text in the "apartamento" column to remove "(blocoAP)" from the DataFrame.

In [423]:
condominium_data.head(3)

      apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0  A101 (blocoAP)                 01/06/2022         05/06/2022         1000.0
1  A101 (blocoAP)                 01/07/2022         03/07/2022         2500.0
2  A102 (blocoAP)                 02/06/2022         02/06/2022         1100.0

In [424]:
condominium_data['apartamento'] = condominium_data['apartamento'].str.replace(' \(blocoAP\)', '', regex=True)
condominium_data['apartamento']

<>:1: SyntaxWarning: invalid escape sequence '\('
<>:1: SyntaxWarning: invalid escape sequence '\('
/tmp/ipykernel_8818/1886529959.py:1: SyntaxWarning: invalid escape sequence '\('
  condominium_data['apartamento'] = condominium_data['apartamento'].str.replace(' \(blocoAP\)', '', regex=True)

0     A101
1     A101
2     A102
3     A102
4     B201
5     B201
6     B202
7     B202
8     C301
9     C301
10    C302
11    C302
12    D401
13    D401
14    D402
15    D402
16    E501
17    E501
18    E502
19    E502
20    F601
21    F601
22    F602
23    F602
24    G701
25    G701
26    G702
27    G702
28    H801
29    H801
Name: apartamento, dtype: object

In [425]:
condominium_data.head(3)

  apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0        A101                 01/06/2022         05/06/2022         1000.0
1        A101                 01/07/2022         03/07/2022         2500.0
2        A102                 02/06/2022         02/06/2022         1100.0

# STAGE 4

### - Challenge Project 1: Online Sales

In the previous steps, we worked with various types of data; now, we can work with time-based data.

In the "Date of sale" (`Data de venda`) column, we have dates in a 'day/month/year' (`dd/mm/yyyy`) format. Convert this data to the datetime type and identify a way to visualize a subset of the data that supports the objectives of the context in which this information is situated.

If you don't recall the problem from the first challenge project, I have included the description of the scenario below to help you find the necessary information:

***
The objective of this project is to analyze the results of an event involving customers of an online retail company. A dataset was collected, containing information on the customers who spent the most on products during the 5-day duration of the event. This analysis will identify the customer who made the largest purchase during the week—who will receive a prize from the store—and, subsequently, it may help the company develop new strategies to attract more customers.
***

In [426]:
sales_data.head()

  Data de venda          Cliente  Valor da compra
0    06/06/2022       ana lucia            836.50
1    06/06/2022  diego armandiu            573.33
2    06/06/2022  diego armandiu            392.80
3    06/06/2022  diego armandiu            512.34
4    07/06/2022  isabely joanes            825.31

In [427]:
sales_data['Data de venda'] = pd.to_datetime(sales_data['Data de venda'], format='%d/%m/%Y')
sales_data['Data de venda']

0    2022-06-06
1    2022-06-06
2    2022-06-06
3    2022-06-06
4    2022-06-07
5    2022-06-07
6    2022-06-07
7    2022-06-07
8    2022-06-08
9    2022-06-08
10   2022-06-08
11   2022-06-08
12   2022-06-09
13   2022-06-09
14   2022-06-09
15   2022-06-09
16   2022-06-10
17   2022-06-10
18   2022-06-10
19   2022-06-10
Name: Data de venda, dtype: datetime64[ns]

In [428]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     datetime64[ns]
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 612.0+ bytes

In [429]:
total_sales = sales_data.groupby(['Cliente'])['Valor da compra'].sum()
total_sales

Cliente
ana lucia           836.50
diego armandiu     1478.47
isabely joanes     2329.30
joo gabriel         386.34
julya meireles     1643.74
maria julia        2086.65
paulo castro        899.16
pedro pasco         311.15
thiago fritzz       885.24
Name: Valor da compra, dtype: float64

### - Challenge Project 2: Condominium Management

As in the first challenge project, we were working with all columns except those involving dates.

In the `payment_dates` (*datas_de_pagamento*) and `agreed_payment_dates` (*datas_combinadas_pagamento*) columns, the dates are in 'day/month/year' (dd/mm/yyyy) format. Convert this data to the `datetime` type and find a way to visualize a subset of the data that contributes to the objectives of the context in which this information is situated.

If you do not recall the problem from the second challenge project, I have included the description of the scenario below to help you find the necessary information:

Managing a condominium complex is a task that requires a great deal of attention and organization. Among the various management responsibilities is the collection of rent from tenants. To ensure the financial health of the property, it is essential that these payments are made regularly and on time. However, we know that this does not always happen. With this in mind, I am proposing a data-handling challenge aimed at analyzing rent payment delays among some residents of a hypothetical condominium.

In [430]:
condominium_data.head()

  apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0        A101                 01/06/2022         05/06/2022         1000.0
1        A101                 01/07/2022         03/07/2022         2500.0
2        A102                 02/06/2022         02/06/2022         1100.0
3        A102                 02/07/2022         06/07/2022         2600.0
4        B201                 03/06/2022         07/06/2022         1200.0

In [431]:
condominium_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

In [432]:
condominium_data['datas_combinadas_pagamento'] = pd.to_datetime(condominium_data['datas_combinadas_pagamento'], format='%d/%m/%Y')
condominium_data['datas_de_pagamento'] = pd.to_datetime(condominium_data['datas_de_pagamento'], format='%d/%m/%Y')

In [433]:
condominium_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     datetime64[ns]
 2   datas_de_pagamento          30 non-null     datetime64[ns]
 3   valor_aluguel               30 non-null     float64
dtypes: datetime64[ns](2), float64(1), object(1)
memory usage: 1.1+ KB

In [434]:
condominium_data.head()

  apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0        A101                 2022-06-01         2022-06-05         1000.0
1        A101                 2022-07-01         2022-07-03         2500.0
2        A102                 2022-06-02         2022-06-02         1100.0
3        A102                 2022-07-02         2022-07-06         2600.0
4        B201                 2022-06-03         2022-06-07         1200.0

In [435]:
condominium_data['payment_delay'] = (condominium_data['datas_de_pagamento'] - condominium_data['datas_combinadas_pagamento']).dt.days

In [436]:
condominium_data.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,payment_delay
0,A101,2022-06-01,2022-06-05,1000.0,4
1,A101,2022-07-01,2022-07-03,2500.0,2
2,A102,2022-06-02,2022-06-02,1100.0,0
3,A102,2022-07-02,2022-07-06,2600.0,4
4,B201,2022-06-03,2022-06-07,1200.0,4

In [437]:
subset = condominium_data.groupby(['apartamento'])['payment_delay'].mean()
subset

apartamento
A101    3.0
A102    2.0
B201    2.0
B202    2.0
C301    4.5
C302    4.0
D401    1.0
D402    4.0
E501    0.5
E502    4.0
F601    4.0
F602    1.5
G701    6.5
G702    2.0
H801    2.0
Name: payment_delay, dtype: float64