# Challenge: do it yourself

During the lessons, we performed tokenization on two columns from our hospitality dataset: `descricao_local` (location description) and `comodidades` (amenities). However, the `descricao_vizinhanca` (neighborhood description) column remains, and it is also worth processing.

Therefore, for this activity, I propose that you carry out the tokenization process for the `descricao_vizinhanca` column found in the `dados_hospedagem.json` dataset.

In [1]:
import pandas as pd

In [3]:
data = pd.read_json('/content/drive/MyDrive/Collab Notebooks - Alura/part_4_pandas_data_transformation/resources/normalized_data_hospitality_v3.json')
data['descricao_vizinhanca']

0       Lower Queen Anne is near the Seattle Center (s...
1       Upper Queen Anne is a really pleasant, unique ...
2       The convenience of being in Seattle but on the...
3       Ballard is lovely, vibrant and one of the most...
4                                                      --
                              ...
3813                                                   --
3814    Quiet, dead end street near I-5. The proximity...
3815                                                   --
3816    Your hosts made Madison Valley their home when...
3817    Despite the quiet, leafy streets of this resid...
Name: descricao_vizinhanca, Length: 3818, dtype: object

In [4]:
data['descricao_vizinhanca'] = data['descricao_vizinhanca'].str.lower()

In [5]:
data['descricao_vizinhanca'] = data['descricao_vizinhanca'].replace('[^a-zA-Z0-9\-\']', ' ', regex=True)
data['descricao_vizinhanca']

<>:1: SyntaxWarning: invalid escape sequence '\-'
<>:1: SyntaxWarning: invalid escape sequence '\-'
/tmp/ipykernel_1321/959812778.py:1: SyntaxWarning: invalid escape sequence '\-'
  data['descricao_vizinhanca'] = data['descricao_vizinhanca'].replace('[^a-zA-Z0-9\-\']', ' ', regex=True)

0       lower queen anne is near the seattle center  s...
1       upper queen anne is a really pleasant  unique ...
2       the convenience of being in seattle but on the...
3       ballard is lovely  vibrant and one of the most...
4                                                      --
                              ...
3813                                                   --
3814    quiet  dead end street near i-5  the proximity...
3815                                                   --
3816    your hosts made madison valley their home when...
3817    despite the quiet  leafy streets of this resid...
Name: descricao_vizinhanca, Length: 3818, dtype: object

In [6]:
data['descricao_vizinhanca'] = data['descricao_vizinhanca'].str.replace('(?<!\w)-(?!\w)', ' ', regex=True)
data['descricao_vizinhanca']

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_1321/294845224.py:1: SyntaxWarning: invalid escape sequence '\w'
  data['descricao_vizinhanca'] = data['descricao_vizinhanca'].str.replace('(?<!\w)-(?!\w)', ' ', regex=True)

0       lower queen anne is near the seattle center  s...
1       upper queen anne is a really pleasant  unique ...
2       the convenience of being in seattle but on the...
3       ballard is lovely  vibrant and one of the most...
4
                              ...
3813
3814    quiet  dead end street near i-5  the proximity...
3815
3816    your hosts made madison valley their home when...
3817    despite the quiet  leafy streets of this resid...
Name: descricao_vizinhanca, Length: 3818, dtype: object

In [8]:
data['descricao_vizinhanca'] = data['descricao_vizinhanca'].str.split()
data['descricao_vizinhanca']

0       [lower, queen, anne, is, near, the, seattle, c...
1       [upper, queen, anne, is, a, really, pleasant, ...
2       [the, convenience, of, being, in, seattle, but...
3       [ballard, is, lovely, vibrant, and, one, of, t...
4                                                      []
                              ...
3813                                                   []
3814    [quiet, dead, end, street, near, i-5, the, pro...
3815                                                   []
3816    [your, hosts, made, madison, valley, their, ho...
3817    [despite, the, quiet, leafy, streets, of, this...
Name: descricao_vizinhanca, Length: 3818, dtype: object

In [9]:
data.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,"[this, clean, and, comfortable, one, bedroom, ...","[lower, queen, anne, is, near, the, seattle, c...",1,1,1,Real Bed,"[Internet, Wireless Internet, Kitchen, Free Pa...",0,0,110
1,10.0,--,1,"[our, century, old, upper, queen, anne, house,...","[upper, queen, anne, is, a, really, pleasant, ...",1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0,0,45
2,10.0,--,1,"[cozy, room, in, two-bedroom, apartment, along...","[the, convenience, of, being, in, seattle, but...",1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0,0,55
3,10.0,--,1,"[very, lovely, and, cozy, room, for, one, conv...","[ballard, is, lovely, vibrant, and, one, of, t...",1,1,1,Pull-out Sofa,"[Internet, Wireless Internet, Kitchen, Free Pa...",0,20,52
4,10.0,--,1,"[the, studio, at, mibbett, hollow', is, in, a,...",[],1,1,1,Real Bed,"[Wireless Internet, Kitchen, Free Parking on P...",0,15,85

In [10]:
data.to_json('normalized_data_hospitality_v4.json', index=False)