# Challenge: do it yourself

In this lesson, we learned how to manipulate temporal data using the `datetime` type. We explored how to convert a column to `datetime` and subsequently work with that data. However, not all the data in the `moveis_disponiveis.json` dataset has been processed yet.

Throughout this course, we discovered how to transform and work with numerical values—for instance, by extracting numbers embedded within text and converting them into a numerical data type, such as `int64` or `float64`.

With this in mind, for this activity, I would like you to convert the data in the `preco` (price) column of the `moveis_disponiveis.json` dataset into the `float64` numerical type. Keep in mind that, before doing so, you must fill in any missing (null) values ​​in that column. A suggestion: replace them with the string `'0.0'`.

In [37]:
import pandas as pd
import numpy as np

In [38]:
dt_data = pd.read_json('/content/drive/MyDrive/Collab Notebooks - Alura/part_4_pandas_data_transformation/resources/moveis_disponiveis_v2.json')

In [39]:
dt_data.head()

    id           data  vaga_disponivel preco
0  857  1451865600000            False  None
1  857  1451952000000            False  None
2  857  1452038400000            False  None
3  857  1452124800000            False  None
4  857  1452211200000            False  None

In [40]:
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  int64
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  object
dtypes: bool(1), int64(2), object(1)
memory usage: 11.5+ MB

In [41]:
dt_data['preco'].fillna('0.0', inplace=True)

/tmp/ipykernel_999/3556533684.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dt_data['preco'].fillna('0.0', inplace=True)

In [42]:
dt_data['preco'] = dt_data['preco'].apply(lambda x: x.replace('$', '').replace(',', '.'))
dt_data['preco']

0            0.0
1            0.0
2            0.0
3            0.0
4            0.0
           ...
364995    140.00
364996    140.00
364997    140.00
364998    140.00
364999       0.0
Name: preco, Length: 365000, dtype: object

In [45]:
dt_data['preco'] = dt_data['preco'].apply(lambda x: x.replace('.', '', x.count('.') - 1) if isinstance(x, str) else x)
dt_data['preco'] = dt_data['preco'].astype(np.float64)
dt_data['preco']

0           0.0
1           0.0
2           0.0
3           0.0
4           0.0
          ...
364995    140.0
364996    140.0
364997    140.0
364998    140.0
364999      0.0
Name: preco, Length: 365000, dtype: float64

In [46]:
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  int64
 2   vaga_disponivel  365000 non-null  bool
 3   preco            365000 non-null  float64
dtypes: bool(1), float64(1), int64(2)
memory usage: 11.5 MB

In [47]:
dt_data.to_json('moveis_disponiveis_v3.json', index=False)