# Understanding the problem

### Churn

Occurs when customers stop doing business with a company.Represents a loss of revenue.I can serve as an indicator of customer satisfaction regarding products/services.


The term "churn" is widely used in the business world and refers to a situation where individuals stop doing business with a company. As data scientists, we know that churn is directly linked to a company's revenue; the more customers who stop doing business, the more money the company loses.


Furthermore, churn can be used as an indicator of customer satisfaction, since a high number of people ceasing to do business may suggest that the service provided is failing to meet customer expectations.

## Which database are we going to work with?

The model we will build using the dataset provided is designed to predict whether or not a given customer will cancel their service with the telecommunications company.


Based on this prediction, we can develop strategies to reduce churn. However, the dataset we received is not yet ready for direct use in machine learning models. Our task is to clean and process it for this specific purpose.


Shall we learn how to do that?

Data:

 - [dataset-telecon.json](https://cdn3.gnarususercontent.com.br/2929-pandas/dataset-telecon.json)

In [14]:
import pandas as pd
import numpy as np

In [15]:
churn_data = pd.read_json('/content/drive/MyDrive/Collab Notebooks - Alura/part_5_pandas_data_cleaning/resources/dataset-telecon.json')
churn_data.head()

,id_cliente,Churn,cliente,telefone,internet,conta
0,0002-ORFBO,nao,"{'genero': 'feminino', 'idoso': 0, 'parceiro':...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'DSL', 'seguranca_online'...","{'contrato': None, 'faturamente_eletronico': N..."
1,0003-MKNFE,nao,"{'genero': 'masculino', 'idoso': 0, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'DSL', 'seguranca_online'...","{'contrato': 'mes a mes', 'faturamente_eletron..."
2,0004-TLHLJ,sim,"{'genero': 'masculino', 'idoso': 0, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'fibra otica', 'seguranca...","{'contrato': 'mes a mes', 'faturamente_eletron..."
3,0011-IGKFF,sim,"{'genero': 'masculino', 'idoso': 1, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'fibra otica', 'seguranca...","{'contrato': 'mes a mes', 'faturamente_eletron..."
4,0013-EXCHZ,sim,"{'genero': 'feminino', 'idoso': 1, 'parceiro':...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'fibra otica', 'seguranca...","{'contrato': 'mes a mes', 'faturamente_eletron..."

In [16]:
churn_data['conta'][0]

{'contrato': None,
 'faturamente_eletronico': None,
 'metodo_pagamento': None,
 'cobranca': {'mensal': None, 'Total': None}}

In [17]:
pd.json_normalize(churn_data['conta']).head()

,contrato,faturamente_eletronico,metodo_pagamento,cobranca.mensal,cobranca.Total
0,None,None,None,NaN,None
1,mes a mes,nao,cheque pelo correio,59.9,542.4
2,mes a mes,sim,cheque eletronico,73.9,280.85
3,mes a mes,sim,cheque eletronico,98.0,1237.85
4,mes a mes,sim,cheque pelo correio,83.9,267.4

In [18]:
pd.json_normalize(churn_data['telefone']).head()

  servico_telefone varias_linhas
0              sim           nao
1              sim           sim
2              sim           nao
3              sim           nao
4              sim           nao

## Transforming data into a tablea

We have learned how to apply the `json_normalize()` method to our dataframes to obtain columns with values ​​in a normalized JSON format. This allows us to expand the keys containing these values ​​into multiple separate columns. However, this approach presents a challenge: having to perform the process manually for each column.

We will now learn a more "Pythonic" way to apply this in a more automated fashion.

### `json_normalize()` method

***
- In a DataFrame ⇾ normalizes only one column

- In a JSON object ⇾ normalizes all nested columns at once
***

In [19]:
import json

In [20]:
with open('/content/drive/MyDrive/Collab Notebooks - Alura/part_5_pandas_data_cleaning/resources/dataset-telecon.json') as f:
  raw_json = json.load(f)

In [ ]:
raw_json

In [23]:
normalized_data = pd.json_normalize(raw_json)
normalized_data.head()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0002-ORFBO,nao,feminino,0,sim,sim,9.0,sim,nao,DSL,...,sim,nao,sim,sim,nao,None,None,None,NaN,None
1,0003-MKNFE,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,...,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.9,542.4
2,0004-TLHLJ,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.9,280.85
3,0011-IGKFF,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.0,1237.85
4,0013-EXCHZ,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,...,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.9,267.4

In [24]:
normalized_data.to_json('telecon_normalized_data_v1.json', index=False)