In [40]:
import pandas as pd
import numpy as np

In [41]:
df_without_outliers = pd.read_json('/content/drive/MyDrive/Collab Notebooks - Alura/part_5_pandas_data_cleaning/resources/subset_without_outliers.json')

# Categorical variable

Imagine that you are conducting a study on people's eye color. In this context, eye color is a categorical variable, since the value we can assign to it is the color itself—blue, green, brown, etc.

We cannot assign a numerical value to this variable; we can only classify it into distinct categories.

## Working with categorical variables

In [42]:
df_without_outliers

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0003-MKNFE,nao,masculino,0,nao,nao,9,sim,sim,DSL,...,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.90,542.40
1,0004-TLHLJ,sim,masculino,0,nao,nao,4,sim,nao,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.90,280.85
2,0011-IGKFF,sim,masculino,1,sim,nao,13,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.00,1237.85
3,0013-EXCHZ,sim,feminino,1,sim,nao,3,sim,nao,fibra otica,...,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.90,267.40
4,0013-MHZWF,nao,feminino,0,nao,sim,9,sim,nao,DSL,...,nao,nao,sim,sim,sim,mes a mes,sim,cartao de credito (automatico),69.40,571.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6997,9987-LUTYD,nao,feminino,0,nao,nao,13,sim,nao,DSL,...,nao,nao,sim,nao,nao,um ano,nao,cheque pelo correio,55.15,742.90
6998,9992-RRAMN,sim,masculino,0,sim,nao,22,sim,sim,fibra otica,...,nao,nao,nao,nao,sim,mes a mes,sim,cheque eletronico,85.10,1873.70
6999,9992-UJOEL,nao,masculino,0,nao,nao,2,sim,nao,DSL,...,sim,nao,nao,nao,nao,mes a mes,sim,cheque pelo correio,50.30,92.75
7000,9993-LHIEB,nao,masculino,0,sim,sim,67,sim,nao,DSL,...,nao,sim,sim,nao,sim,dois anos,nao,cheque pelo correio,67.85,4627.65
7001,9995-HOTOH,nao,masculino,0,sim,sim,63,nao,sem servico de telefone,DSL,...,sim,sim,nao,sim,sim,dois anos,nao,cheque eletronico,59.00,3707.60

Note that we have an initial column called `id_cliente`. The ID is unique to each of the 7,002 customers registered in our database.

Although this is a categorical column, it makes no sense to keep it in our dataset; while it might be important in other contexts, it provides no relevant information for our machine learning model.

So, we’re going to drop this column to help improve the performance of our model’s process.

### Replacing values

In [43]:
df_without_outliers.drop('id_cliente', axis=1)

,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,internet.seguranca_online,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,nao,masculino,0,nao,nao,9,sim,sim,DSL,nao,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.90,542.40
1,sim,masculino,0,nao,nao,4,sim,nao,fibra otica,nao,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.90,280.85
2,sim,masculino,1,sim,nao,13,sim,nao,fibra otica,nao,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.00,1237.85
3,sim,feminino,1,sim,nao,3,sim,nao,fibra otica,nao,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.90,267.40
4,nao,feminino,0,nao,sim,9,sim,nao,DSL,nao,nao,nao,sim,sim,sim,mes a mes,sim,cartao de credito (automatico),69.40,571.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6997,nao,feminino,0,nao,nao,13,sim,nao,DSL,sim,nao,nao,sim,nao,nao,um ano,nao,cheque pelo correio,55.15,742.90
6998,sim,masculino,0,sim,nao,22,sim,sim,fibra otica,nao,nao,nao,nao,nao,sim,mes a mes,sim,cheque eletronico,85.10,1873.70
6999,nao,masculino,0,nao,nao,2,sim,nao,DSL,nao,sim,nao,nao,nao,nao,mes a mes,sim,cheque pelo correio,50.30,92.75
7000,nao,masculino,0,sim,sim,67,sim,nao,DSL,sim,nao,sim,sim,nao,sim,dois anos,nao,cheque pelo correio,67.85,4627.65
7001,nao,masculino,0,sim,sim,63,nao,sem servico de telefone,DSL,sim,sim,sim,nao,sim,sim,dois anos,nao,cheque eletronico,59.00,3707.60

In [44]:
df_without_outliers.to_json('subset_without_outliers_v2.json')

In [45]:
df_without_id = df_without_outliers.drop('id_cliente', axis=1).copy()

In [46]:
df_without_id

,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,internet.seguranca_online,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,nao,masculino,0,nao,nao,9,sim,sim,DSL,nao,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.90,542.40
1,sim,masculino,0,nao,nao,4,sim,nao,fibra otica,nao,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.90,280.85
2,sim,masculino,1,sim,nao,13,sim,nao,fibra otica,nao,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.00,1237.85
3,sim,feminino,1,sim,nao,3,sim,nao,fibra otica,nao,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.90,267.40
4,nao,feminino,0,nao,sim,9,sim,nao,DSL,nao,nao,nao,sim,sim,sim,mes a mes,sim,cartao de credito (automatico),69.40,571.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6997,nao,feminino,0,nao,nao,13,sim,nao,DSL,sim,nao,nao,sim,nao,nao,um ano,nao,cheque pelo correio,55.15,742.90
6998,sim,masculino,0,sim,nao,22,sim,sim,fibra otica,nao,nao,nao,nao,nao,sim,mes a mes,sim,cheque eletronico,85.10,1873.70
6999,nao,masculino,0,nao,nao,2,sim,nao,DSL,nao,sim,nao,nao,nao,nao,mes a mes,sim,cheque pelo correio,50.30,92.75
7000,nao,masculino,0,sim,sim,67,sim,nao,DSL,sim,nao,sim,sim,nao,sim,dois anos,nao,cheque pelo correio,67.85,4627.65
7001,nao,masculino,0,sim,sim,63,nao,sem servico de telefone,DSL,sim,sim,sim,nao,sim,sim,dois anos,nao,cheque eletronico,59.00,3707.60

# Binary categorical variables

Binary categorical variables are variables that have only two mutually exclusive categories or possible responses.

They are used to classify data into opposing groups, such as "yes" or "no," "true" or "false," and "success" or "failure."

## Working with binary variables

In our case, we have the following columns:
- `Churn` (yes/no),
- `cliente.idoso` (0/1),
- `cliente.genero` (male/female),
- `cliente.parceiro` (yes/no),
- `cliente.dependentes` (yes/no).

Among various others, it would be useful to check the possible values ​​for each of our columns.

Our goal is to replace binary values ​​with 0s and 1s. Machine learning models perform much better when provided with numerical data.

In [47]:
mapping = {
    'nao': 0,
    'sim': 1,
    'masculino': 0,
    'feminino': 1
}

In [48]:
for col in df_without_id.columns:
  print(f'Column: {col}')
  print(df_without_id[col].unique())
  print('-' * 40)

Column: Churn
['nao' 'sim']
----------------------------------------
Column: cliente.genero
['masculino' 'feminino']
----------------------------------------
Column: cliente.idoso
[0 1]
----------------------------------------
Column: cliente.parceiro
['nao' 'sim']
----------------------------------------
Column: cliente.dependentes
['nao' 'sim']
----------------------------------------
Column: cliente.tempo_servico
[ 9  4 13  3 71 63  7 66 54 72  5 56 34  1 45 50 23 55 26 69 37 49 67 20
 43 59 12 27  2 25 29 14 35 64 39 40 11  6 30 70 57 58 16 32 33 10 21 61
 15 44 22 24 19 47 62 46 52  8 60 48 28 41 53 68 31 36 17 18 65 51 38 42]
----------------------------------------
Column: telefone.servico_telefone
['sim' 'nao']
----------------------------------------
Column: telefone.varias_linhas
['sim' 'nao' 'sem servico de telefone']
----------------------------------------
Column: internet.servico_internet
['DSL' 'fibra otica' 'nao']
----------------------------------------
Column: internet.seguranca_online
['nao' 'sim' 'sem servico de internet']
----------------------------------------
Column: internet.backup_online
['nao' 'sim' 'sem servico de internet']
----------------------------------------
Column: internet.protecao_dispositivo
['nao' 'sim' 'sem servico de internet']
----------------------------------------
Column: internet.suporte_tecnico
['nao' 'sim' 'sem servico de internet']
----------------------------------------
Column: internet.tv_streaming
['nao' 'sim' 'sem servico de internet']
----------------------------------------
Column: internet.filmes_streaming
['sim' 'nao' 'sem servico de internet']
----------------------------------------
Column: conta.contrato
['mes a mes' 'dois anos' 'um ano']
----------------------------------------
Column: conta.faturamente_eletronico
['nao' 'sim']
----------------------------------------
Column: conta.metodo_pagamento
['cheque pelo correio' 'cheque eletronico'
 'cartao de credito (automatico)' 'transferencia bancaria (automatica)']
----------------------------------------
Column: conta.cobranca.mensal
[59.9  73.9  98.   ... 91.75 68.8  67.85]
----------------------------------------
Column: conta.cobranca.Total
[ 542.4   280.85 1237.85 ...  742.9  4627.65 3707.6 ]
----------------------------------------

As noted, there are columns that contain more than two values, and some of these might be the ones we are mapping.

Therefore, we must be careful not to perform our mapping on non-binary columns.

### Replacing values

In [49]:
columns = ['telefone.servico_telefone', 'Churn', 'cliente.parceiro', 'cliente.dependentes', 'conta.faturamente_eletronico']

In [50]:
df_without_id[columns] = df_without_id[columns].replace(mapping)
df_without_id

/tmp/ipykernel_3364/4282660255.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_without_id[columns] = df_without_id[columns].replace(mapping)

,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,internet.seguranca_online,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0,masculino,0,0,0,9,1,sim,DSL,nao,nao,nao,nao,nao,sim,mes a mes,0,cheque pelo correio,59.90,542.40
1,1,masculino,0,0,0,4,1,nao,fibra otica,nao,nao,sim,nao,nao,nao,mes a mes,1,cheque eletronico,73.90,280.85
2,1,masculino,1,1,0,13,1,nao,fibra otica,nao,sim,sim,nao,sim,sim,mes a mes,1,cheque eletronico,98.00,1237.85
3,1,feminino,1,1,0,3,1,nao,fibra otica,nao,nao,nao,sim,sim,nao,mes a mes,1,cheque pelo correio,83.90,267.40
4,0,feminino,0,0,1,9,1,nao,DSL,nao,nao,nao,sim,sim,sim,mes a mes,1,cartao de credito (automatico),69.40,571.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6997,0,feminino,0,0,0,13,1,nao,DSL,sim,nao,nao,sim,nao,nao,um ano,0,cheque pelo correio,55.15,742.90
6998,1,masculino,0,1,0,22,1,sim,fibra otica,nao,nao,nao,nao,nao,sim,mes a mes,1,cheque eletronico,85.10,1873.70
6999,0,masculino,0,0,0,2,1,nao,DSL,nao,sim,nao,nao,nao,nao,mes a mes,1,cheque pelo correio,50.30,92.75
7000,0,masculino,0,1,1,67,1,nao,DSL,sim,nao,sim,sim,nao,sim,dois anos,0,cheque pelo correio,67.85,4627.65
7001,0,masculino,0,1,1,63,0,sem servico de telefone,DSL,sim,sim,sim,nao,sim,sim,dois anos,0,cheque eletronico,59.00,3707.60

In [51]:
for col in df_without_id.columns:
  print(f'Column: {col}')
  print(df_without_id[col].unique())
  print('-' * 40)

Column: Churn
[0 1]
----------------------------------------
Column: cliente.genero
['masculino' 'feminino']
----------------------------------------
Column: cliente.idoso
[0 1]
----------------------------------------
Column: cliente.parceiro
[0 1]
----------------------------------------
Column: cliente.dependentes
[0 1]
----------------------------------------
Column: cliente.tempo_servico
[ 9  4 13  3 71 63  7 66 54 72  5 56 34  1 45 50 23 55 26 69 37 49 67 20
 43 59 12 27  2 25 29 14 35 64 39 40 11  6 30 70 57 58 16 32 33 10 21 61
 15 44 22 24 19 47 62 46 52  8 60 48 28 41 53 68 31 36 17 18 65 51 38 42]
----------------------------------------
Column: telefone.servico_telefone
[1 0]
----------------------------------------
Column: telefone.varias_linhas
['sim' 'nao' 'sem servico de telefone']
----------------------------------------
Column: internet.servico_internet
['DSL' 'fibra otica' 'nao']
----------------------------------------
Column: internet.seguranca_online
['nao' 'sim' 'sem servico de internet']
----------------------------------------
Column: internet.backup_online
['nao' 'sim' 'sem servico de internet']
----------------------------------------
Column: internet.protecao_dispositivo
['nao' 'sim' 'sem servico de internet']
----------------------------------------
Column: internet.suporte_tecnico
['nao' 'sim' 'sem servico de internet']
----------------------------------------
Column: internet.tv_streaming
['nao' 'sim' 'sem servico de internet']
----------------------------------------
Column: internet.filmes_streaming
['sim' 'nao' 'sem servico de internet']
----------------------------------------
Column: conta.contrato
['mes a mes' 'dois anos' 'um ano']
----------------------------------------
Column: conta.faturamente_eletronico
[0 1]
----------------------------------------
Column: conta.metodo_pagamento
['cheque pelo correio' 'cheque eletronico'
 'cartao de credito (automatico)' 'transferencia bancaria (automatica)']
----------------------------------------
Column: conta.cobranca.mensal
[59.9  73.9  98.   ... 91.75 68.8  67.85]
----------------------------------------
Column: conta.cobranca.Total
[ 542.4   280.85 1237.85 ...  742.9  4627.65 3707.6 ]
----------------------------------------

# Non-binary categorical variables

Non-binary categorical variables are qualitative data that have three or more possible categories, with no inherent order or hierarchy among them.

A classic example is the variable "eye color," which can take on multiple distinct values ​​such as blue, green, brown, or black.

## One Hot Encoder (or Dummy)
Exemple:

In [52]:
s = pd.Series(list('abca'))
s

0    a
1    b
2    c
3    a
dtype: object

In [53]:
pd.get_dummies(s)

       a      b      c
0   True  False  False
1  False   True  False
2  False  False   True
3   True  False  False

The `get_dummies()` method is, in fact, an implementation of the One-Hot Encoding technique. It returns a dataframe containing four samples—indexed from 0 to 3—and three columns: 'a', 'b', and 'c'.

This technique uses categorical variables to create new columns, each named after one of the distinct categories. Since there were three categories, three columns were created in the table.

At index 0, the value in the first column ('a') serves as an answer to the following question: "Is the entry at index 0 equal to 'a'?" Because the value is `True`, the answer is "yes"—which makes sense, as 'a' was the value present at index 0 in the original data.

Since the other two columns do not correspond to the value at index 0, they are populated with the value `False`, signifying "no."

The value at index 1 belongs to category 'b', so a `True` value—corresponding to "yes"—is marked in column 'b'. As before, the remaining columns are set to `False`, representing "no".

This process is repeated for the other samples at each index. This is what the `get_dummies()` method does: it creates new columns and assigns `True` wherever the corresponding index value is indicated in the original dataframe.

### Working with non-binary variables

In [54]:
df_without_id.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7002 entries, 0 to 7001
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Churn                          7002 non-null   int64
 1   cliente.genero                 7002 non-null   object
 2   cliente.idoso                  7002 non-null   int64
 3   cliente.parceiro               7002 non-null   int64
 4   cliente.dependentes            7002 non-null   int64
 5   cliente.tempo_servico          7002 non-null   int64
 6   telefone.servico_telefone      7002 non-null   int64
 7   telefone.varias_linhas         7002 non-null   object
 8   internet.servico_internet      7002 non-null   object
 9   internet.seguranca_online      7002 non-null   object
 10  internet.backup_online         7002 non-null   object
 11  internet.protecao_dispositivo  7002 non-null   object
 12  internet.suporte_tecnico       7002 non-null   object
 13  internet.tv_streaming          7002 non-null   object
 14  internet.filmes_streaming      7002 non-null   object
 15  conta.contrato                 7002 non-null   object
 16  conta.faturamente_eletronico   7002 non-null   int64
 17  conta.metodo_pagamento         7002 non-null   object
 18  conta.cobranca.mensal          7002 non-null   float64
 19  conta.cobranca.Total           7002 non-null   float64
dtypes: float64(2), int64(7), object(11)
memory usage: 1.4+ MB

Variables with a dtype set to 'object' will be interpreted as categorical columns.

Shall we apply this to our dataset?

Keep in mind that, in computing, `True` corresponds to the value 1, and `False` to 0.

Therefore, we will use the parameter `dtype=int` to ensure consistency resulting in 0s and 1s within our dataframe.

In [55]:
pd.get_dummies(df_without_id, dtype=int)

,Churn,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,conta.faturamente_eletronico,conta.cobranca.mensal,conta.cobranca.Total,cliente.genero_feminino,...,internet.filmes_streaming_nao,internet.filmes_streaming_sem servico de internet,internet.filmes_streaming_sim,conta.contrato_dois anos,conta.contrato_mes a mes,conta.contrato_um ano,conta.metodo_pagamento_cartao de credito (automatico),conta.metodo_pagamento_cheque eletronico,conta.metodo_pagamento_cheque pelo correio,conta.metodo_pagamento_transferencia bancaria (automatica)
0,0,0,0,0,9,1,0,59.90,542.40,0,...,0,0,1,0,1,0,0,0,1,0
1,1,0,0,0,4,1,1,73.90,280.85,0,...,1,0,0,0,1,0,0,1,0,0
2,1,1,1,0,13,1,1,98.00,1237.85,0,...,0,0,1,0,1,0,0,1,0,0
3,1,1,1,0,3,1,1,83.90,267.40,1,...,1,0,0,0,1,0,0,0,1,0
4,0,0,0,1,9,1,1,69.40,571.45,1,...,0,0,1,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6997,0,0,0,0,13,1,0,55.15,742.90,1,...,1,0,0,0,0,1,0,0,1,0
6998,1,0,1,0,22,1,1,85.10,1873.70,0,...,0,0,1,0,1,0,0,1,0,0
6999,0,0,0,0,2,1,1,50.30,92.75,0,...,1,0,0,0,1,0,0,0,1,0
7000,0,0,1,1,67,1,0,67.85,4627.65,0,...,0,0,1,1,0,0,0,0,1,0
7001,0,0,1,1,63,0,0,59.00,3707.60,0,...,0,0,1,1,0,0,0,1,0,0

In [56]:
df_without_id.to_json('subset_without_id.json')

In [57]:
df_dummies = pd.get_dummies(df_without_id, dtype=int).copy()
df_dummies.head()

,Churn,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,conta.faturamente_eletronico,conta.cobranca.mensal,conta.cobranca.Total,cliente.genero_feminino,...,internet.filmes_streaming_nao,internet.filmes_streaming_sem servico de internet,internet.filmes_streaming_sim,conta.contrato_dois anos,conta.contrato_mes a mes,conta.contrato_um ano,conta.metodo_pagamento_cartao de credito (automatico),conta.metodo_pagamento_cheque eletronico,conta.metodo_pagamento_cheque pelo correio,conta.metodo_pagamento_transferencia bancaria (automatica)
0,0,0,0,0,9,1,0,59.9,542.40,0,...,0,0,1,0,1,0,0,0,1,0
1,1,0,0,0,4,1,1,73.9,280.85,0,...,1,0,0,0,1,0,0,1,0,0
2,1,1,1,0,13,1,1,98.0,1237.85,0,...,0,0,1,0,1,0,0,1,0,0
3,1,1,1,0,3,1,1,83.9,267.40,1,...,1,0,0,0,1,0,0,0,1,0
4,0,0,0,1,9,1,1,69.4,571.45,1,...,0,0,1,0,1,0,1,0,0,0

In [59]:
df_dummies.columns

Index(['Churn', 'cliente.idoso', 'cliente.parceiro', 'cliente.dependentes',
       'cliente.tempo_servico', 'telefone.servico_telefone',
       'conta.faturamente_eletronico', 'conta.cobranca.mensal',
       'conta.cobranca.Total', 'cliente.genero_feminino',
       'cliente.genero_masculino', 'telefone.varias_linhas_nao',
       'telefone.varias_linhas_sem servico de telefone',
       'telefone.varias_linhas_sim', 'internet.servico_internet_DSL',
       'internet.servico_internet_fibra otica',
       'internet.servico_internet_nao', 'internet.seguranca_online_nao',
       'internet.seguranca_online_sem servico de internet',
       'internet.seguranca_online_sim', 'internet.backup_online_nao',
       'internet.backup_online_sem servico de internet',
       'internet.backup_online_sim', 'internet.protecao_dispositivo_nao',
       'internet.protecao_dispositivo_sem servico de internet',
       'internet.protecao_dispositivo_sim', 'internet.suporte_tecnico_nao',
       'internet.suporte_tecnico_sem servico de internet',
       'internet.suporte_tecnico_sim', 'internet.tv_streaming_nao',
       'internet.tv_streaming_sem servico de internet',
       'internet.tv_streaming_sim', 'internet.filmes_streaming_nao',
       'internet.filmes_streaming_sem servico de internet',
       'internet.filmes_streaming_sim', 'conta.contrato_dois anos',
       'conta.contrato_mes a mes', 'conta.contrato_um ano',
       'conta.metodo_pagamento_cartao de credito (automatico)',
       'conta.metodo_pagamento_cheque eletronico',
       'conta.metodo_pagamento_cheque pelo correio',
       'conta.metodo_pagamento_transferencia bancaria (automatica)'],
      dtype='object')

In [60]:
df_dummies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7002 entries, 0 to 7001
Data columns (total 42 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Churn                                                       7002 non-null   int64
 1   cliente.idoso                                               7002 non-null   int64
 2   cliente.parceiro                                            7002 non-null   int64
 3   cliente.dependentes                                         7002 non-null   int64
 4   cliente.tempo_servico                                       7002 non-null   int64
 5   telefone.servico_telefone                                   7002 non-null   int64
 6   conta.faturamente_eletronico                                7002 non-null   int64
 7   conta.cobranca.mensal                                       7002 non-null   float64
 8   conta.cobranca.Total                                        7002 non-null   float64
 9   cliente.genero_feminino                                     7002 non-null   int64
 10  cliente.genero_masculino                                    7002 non-null   int64
 11  telefone.varias_linhas_nao                                  7002 non-null   int64
 12  telefone.varias_linhas_sem servico de telefone              7002 non-null   int64
 13  telefone.varias_linhas_sim                                  7002 non-null   int64
 14  internet.servico_internet_DSL                               7002 non-null   int64
 15  internet.servico_internet_fibra otica                       7002 non-null   int64
 16  internet.servico_internet_nao                               7002 non-null   int64
 17  internet.seguranca_online_nao                               7002 non-null   int64
 18  internet.seguranca_online_sem servico de internet           7002 non-null   int64
 19  internet.seguranca_online_sim                               7002 non-null   int64
 20  internet.backup_online_nao                                  7002 non-null   int64
 21  internet.backup_online_sem servico de internet              7002 non-null   int64
 22  internet.backup_online_sim                                  7002 non-null   int64
 23  internet.protecao_dispositivo_nao                           7002 non-null   int64
 24  internet.protecao_dispositivo_sem servico de internet       7002 non-null   int64
 25  internet.protecao_dispositivo_sim                           7002 non-null   int64
 26  internet.suporte_tecnico_nao                                7002 non-null   int64
 27  internet.suporte_tecnico_sem servico de internet            7002 non-null   int64
 28  internet.suporte_tecnico_sim                                7002 non-null   int64
 29  internet.tv_streaming_nao                                   7002 non-null   int64
 30  internet.tv_streaming_sem servico de internet               7002 non-null   int64
 31  internet.tv_streaming_sim                                   7002 non-null   int64
 32  internet.filmes_streaming_nao                               7002 non-null   int64
 33  internet.filmes_streaming_sem servico de internet           7002 non-null   int64
 34  internet.filmes_streaming_sim                               7002 non-null   int64
 35  conta.contrato_dois anos                                    7002 non-null   int64
 36  conta.contrato_mes a mes                                    7002 non-null   int64
 37  conta.contrato_um ano                                       7002 non-null   int64
 38  conta.metodo_pagamento_cartao de credito (automatico)       7002 non-null   int64
 39  conta.metodo_pagamento_cheque eletronico                    7002 non-null   int64
 40  conta.metodo_pagamento_cheque pelo correio                  7002 non-null   int64
 41  conta.metodo_pagamento_transferencia bancaria (automatica)  7002 non-null   int64
dtypes: float64(2), int64(40)
memory usage: 2.5 MB

Now, our machine learning model can work with these values ​​in a more optimized and accurate way. If you feed this dataset into a neural network, it will function exclusively with numerical variables—exactly as we intended.

In this way, the model will be able to capture non-linear relationships between the numerical variables and the categorical variables (for which dummy columns have been created).

Our dataset is now ready to be used in a machine learning model!

In [61]:
df_dummies.to_json('subset_dummies.json')