# Identification of duplicate data

Duplicate samples are rows that contain exactly the same values ​​in all columns. In other words, they are exact copies of other rows present in the dataset.

In [77]:
import pandas as pd

In [78]:
no_empty_data = pd.read_json('/content/drive/MyDrive/Collab Notebooks - Alura/part_5_pandas_data_cleaning/resources/churn_subset_without_empty_data_v1.json')

***
The Pandas library provides the `duplicated()` method, which returns a Boolean Series where `False` values ​​indicate that there is no duplication of this set of data, and `True` values ​​indicate that there is duplicate data.
***

### Identifying and handling duplicate data

In [79]:
no_empty_data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7113     True
7114     True
7115     True
7116     True
7117     True
Length: 7118, dtype: bool

In [80]:
no_empty_data.duplicated().sum()

np.int64(75)

In [81]:
duplicated_filter = no_empty_data.duplicated()
duplicated_filter

0       False
1       False
2       False
3       False
4       False
        ...
7113     True
7114     True
7115     True
7116     True
7117     True
Length: 7118, dtype: bool

In [82]:
no_empty_data[duplicated_filter]

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
7043,0675-NCDYU,nao,feminino,0,sim,sim,72.0,sim,sim,fibra otica,...,sim,sim,sim,sim,sim,dois anos,sim,cartao de credito (automatico),116.40,8543.25
7044,6754-LZUKA,nao,masculino,0,sim,nao,61.0,sim,sim,DSL,...,sim,sim,nao,sim,sim,dois anos,nao,transferencia bancaria (automatica),80.90,4932.50
7045,2192-CKRLV,nao,feminino,0,sim,nao,72.0,nao,sem servico de telefone,DSL,...,sim,sim,nao,nao,sim,dois anos,sim,cheque eletronico,49.20,3580.95
7046,9170-ARBTB,nao,feminino,0,sim,sim,52.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,um ano,nao,cartao de credito (automatico),19.60,1012.40
7047,0447-BEMNG,sim,feminino,0,sim,nao,48.0,nao,sem servico de telefone,DSL,...,nao,sim,nao,nao,sim,mes a mes,sim,transferencia bancaria (automatica),45.30,2145.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7113,5792-JALQC,nao,feminino,1,nao,nao,52.0,sim,sim,DSL,...,nao,sim,nao,nao,nao,dois anos,nao,transferencia bancaria (automatica),59.85,3103.25
7114,5172-RKOCB,nao,masculino,0,sim,nao,72.0,sim,sim,fibra otica,...,sim,nao,sim,sim,sim,dois anos,sim,cartao de credito (automatico),108.95,7875.00
7115,1934-MKPXS,nao,masculino,0,sim,sim,33.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,um ano,nao,cartao de credito (automatico),20.10,620.55
7116,5959-BELXA,sim,masculino,1,nao,nao,32.0,sim,sim,fibra otica,...,nao,nao,nao,sim,sim,mes a mes,sim,cartao de credito (automatico),96.15,3019.25
7117,4452-QIIEB,nao,masculino,0,nao,nao,7.0,sim,nao,DSL,...,nao,nao,nao,nao,nao,mes a mes,nao,cheque pelo correio,43.90,278.40

With this analysis, we now know how many duplicate samples there are, which ones they are, and how to locate them within the dataset. But what should be done with these samples? They should be removed from the dataset.

There are three main reasons for removing duplicate samples:

- Model bias: If a dataset contains duplicate samples, a machine learning model might assign disproportionate importance to these repeated entries.
- Improved model performance: Including duplicate samples requires additional calculations and processing power; furthermore, it is computationally wasteful to process samples that have the same values ​​and convey the same information.
- Higher-quality results: By ensuring the data consists only of unique entries—free from repetitions—the information becomes more relevant to the model.
***
The Pandas library provides the `drop_duplicates()` method for removing duplicate samples.
***

In [83]:
no_empty_data.drop_duplicates(inplace=True)

In [84]:
no_empty_data.duplicated().sum()

np.int64(0)

# Identification of null data

In [85]:
no_empty_data.isna()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7039,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7040,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7041,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7042,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [86]:
no_empty_data.isna().sum()

id_cliente                        0
Churn                             0
cliente.genero                    0
cliente.idoso                     0
cliente.parceiro                  0
cliente.dependentes               0
cliente.tempo_servico             8
telefone.servico_telefone         0
telefone.varias_linhas            0
internet.servico_internet         0
internet.seguranca_online         0
internet.backup_online            0
internet.protecao_dispositivo     0
internet.suporte_tecnico          0
internet.tv_streaming             0
internet.filmes_streaming         0
conta.contrato                   31
conta.faturamente_eletronico     17
conta.metodo_pagamento           26
conta.cobranca.mensal            17
conta.cobranca.Total             15
dtype: int64

In [87]:
no_empty_data.isna().sum().sum()

np.int64(114)

After executing the cell, we have a total of 114 null values ​​in the dataset. However, this does not represent the number of samples containing null values, as some rows may have more than one null value in different columns.

Therefore, we will perform a filtering operation that returns a *dataframe* containing all rows that have at least one null value in any of the columns.

In [88]:
no_empty_data[no_empty_data.isna().any(axis=1)]

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0002-ORFBO,nao,feminino,0,sim,sim,9.0,sim,nao,DSL,...,sim,nao,sim,sim,nao,None,None,None,NaN,NaN
9,0016-QLJIS,nao,feminino,0,sim,sim,NaN,sim,sim,DSL,...,sim,sim,sim,sim,sim,dois anos,sim,cheque pelo correio,90.45,5957.90
176,0282-NVSJS,nao,feminino,1,sim,sim,NaN,nao,sem servico de telefone,DSL,...,nao,nao,sim,nao,nao,mes a mes,sim,cheque pelo correio,29.30,355.90
181,0295-QVKPB,nao,masculino,0,nao,nao,NaN,sim,nao,DSL,...,nao,sim,sim,sim,nao,mes a mes,sim,cartao de credito (automatico),63.95,318.10
437,0639-TSIQW,sim,feminino,0,nao,nao,67.0,sim,sim,fibra otica,...,sim,sim,nao,sim,nao,None,None,cartao de credito (automatico),NaN,6886.25
751,1095-WGNGG,nao,feminino,0,sim,nao,NaN,sim,sim,fibra otica,...,sim,nao,nao,sim,sim,dois anos,sim,transferencia bancaria (automatica),101.05,5971.25
963,1396-QWFBJ,sim,feminino,0,sim,sim,21.0,sim,nao,fibra otica,...,sim,nao,nao,nao,nao,None,sim,None,NaN,1565.70
1604,2333-KWEWW,nao,masculino,0,nao,nao,18.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,None,nao,None,20.05,NaN
1605,2335-GSODA,nao,masculino,0,nao,sim,23.0,nao,sem servico de telefone,DSL,...,nao,sim,sim,nao,nao,None,nao,None,NaN,NaN
1606,2338-BQEZT,nao,feminino,0,nao,nao,55.0,sim,nao,DSL,...,nao,nao,nao,nao,nao,None,sim,cartao de credito (automatico),NaN,NaN
1608,2344-JMOGN,sim,masculino,0,sim,nao,9.0,sim,nao,fibra otica,...,sim,sim,sim,sim,nao,mes a mes,None,cheque pelo correio,NaN,890.60
2036,2931-FSOHN,nao,masculino,1,nao,nao,13.0,sim,nao,DSL,...,sim,nao,nao,sim,nao,mes a mes,sim,None,59.90,788.35
2037,2931-SVLTV,nao,masculino,0,sim,sim,40.0,sim,sim,fibra otica,...,sim,nao,sim,sim,sim,None,None,None,NaN,NaN
2039,2931-XIQBR,nao,feminino,0,sim,sim,50.0,sim,nao,fibra otica,...,nao,sim,sim,sim,sim,None,None,cheque pelo correio,103.05,5153.50
3523,4994-OBRSZ,nao,masculino,0,nao,sim,NaN,sim,nao,DSL,...,sim,sim,sim,nao,sim,dois anos,nao,transferencia bancaria (automatica),76.10,1054.80
4712,6637-KYRCV,nao,feminino,0,sim,sim,5.0,nao,sem servico de telefone,DSL,...,sim,nao,nao,nao,nao,None,None,None,NaN,NaN
4716,6646-QVXLR,sim,masculino,1,sim,nao,62.0,sim,sim,fibra otica,...,sim,sim,nao,sim,sim,None,sim,cheque eletronico,NaN,NaN
4718,6647-ZEDXT,nao,feminino,0,nao,nao,30.0,sim,sim,fibra otica,...,sim,sim,sim,sim,sim,None,nao,None,110.45,3327.05
4721,6650-VJONK,nao,masculino,0,nao,nao,1.0,sim,nao,DSL,...,nao,nao,nao,nao,nao,None,sim,transferencia bancaria (automatica),NaN,NaN
4725,6653-CBBOM,sim,feminino,0,nao,nao,1.0,sim,nao,fibra otica,...,nao,nao,nao,nao,nao,None,sim,None,70.30,70.30
4728,6656-GULJQ,nao,masculino,0,sim,sim,72.0,sim,sim,DSL,...,nao,sim,sim,sim,sim,None,None,cartao de credito (automatico),83.55,NaN
4731,6661-HBGWL,sim,feminino,1,nao,nao,42.0,sim,sim,fibra otica,...,sim,sim,nao,sim,sim,None,sim,None,104.75,NaN
4733,6664-FPDAC,sim,feminino,1,nao,nao,56.0,sim,sim,fibra otica,...,sim,sim,sim,sim,sim,None,sim,cheque eletronico,NaN,NaN
4738,6680-NENYN,sim,feminino,0,nao,nao,43.0,sim,sim,fibra otica,...,sim,sim,nao,sim,sim,None,sim,None,104.60,4759.85
4740,6681-ZSEXG,nao,masculino,0,sim,nao,56.0,sim,sim,DSL,...,sim,sim,nao,nao,nao,dois anos,nao,None,59.50,3389.25
4745,6685-XSHHU,nao,masculino,0,sim,sim,60.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,None,None,20.95,NaN
4749,6689-TCZHQ,sim,feminino,1,nao,nao,5.0,sim,nao,fibra otica,...,nao,nao,nao,nao,sim,mes a mes,None,None,78.95,378.40
4751,6691-CCIHA,nao,feminino,0,sim,nao,62.0,sim,sim,DSL,...,sim,nao,sim,sim,sim,None,sim,None,84.95,5150.55
4755,6693-FRIRW,nao,masculino,0,nao,nao,18.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,None,nao,None,NaN,NaN
4762,6702-OHFWR,sim,masculino,1,nao,nao,1.0,nao,sem servico de telefone,DSL,...,sim,sim,nao,nao,sim,None,None,None,43.30,43.30
5273,7435-ZNUYY,nao,masculino,0,nao,nao,NaN,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,um ano,nao,cheque pelo correio,20.60,116.60
5276,7445-WMRBW,nao,feminino,0,nao,nao,NaN,sim,sim,DSL,...,sim,sim,sim,sim,nao,um ano,sim,transferencia bancaria (automatica),73.85,3581.40
5396,7606-BPHHN,nao,masculino,0,nao,nao,72.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,None,sim,cartao de credito (automatico),19.80,1468.75
5397,7607-QKKTJ,nao,masculino,0,sim,sim,45.0,sim,sim,fibra otica,...,sim,sim,nao,nao,sim,None,None,None,NaN,4368.85
5402,7611-YKYTC,nao,masculino,0,sim,sim,22.0,sim,nao,fibra otica,...,nao,nao,nao,nao,nao,None,nao,transferencia bancaria (automatica),NaN,NaN
5404,7614-QVWQL,sim,masculino,0,sim,sim,49.0,nao,sem servico de telefone,DSL,...,sim,nao,nao,sim,sim,None,None,None,NaN,NaN
5410,7622-FWGEW,nao,masculino,1,sim,nao,56.0,sim,nao,DSL,...,sim,sim,sim,sim,sim,None,sim,None,NaN,4824.45
5412,7623-HKYRK,nao,masculino,0,nao,sim,6.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,None,None,None,19.70,111.65
5415,7627-JKIAZ,sim,feminino,0,sim,nao,37.0,sim,sim,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,None,78.95,2839.65
6007,8480-PPONV,nao,masculino,0,sim,sim,62.0,sim,sim,fibra otica,...,sim,sim,sim,sim,sim,None,None,transferencia bancaria (automatica),NaN,7159.05
6134,8690-UPCZI,nao,masculino,0,sim,sim,NaN,sim,sim,DSL,...,nao,nao,sim,sim,nao,um ano,nao,transferencia bancaria (automatica),69.05,1958.45
6181,8748-HFWBO,nao,masculino,0,sim,sim,19.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,None,None,None,19.90,357.70
6652,9465-RWMXL,sim,masculino,0,sim,nao,32.0,sim,sim,fibra otica,...,nao,sim,nao,nao,nao,None,None,None,78.90,2447.95
6655,9470-RTWDV,nao,masculino,0,sim,sim,26.0,sim,sim,DSL,...,nao,sim,sim,sim,sim,None,None,None,82.00,2083.10
6656,9470-XCCEM,nao,masculino,0,sim,sim,35.0,sim,sim,fibra otica,...,sim,nao,nao,sim,nao,None,sim,None,89.65,3161.60

Given this information, we need to decide whether to remove samples that contain null values ​​or to fill those nulls with other data.
***
First, let’s consider the option of filling the null values ​​with other data—after all, removing samples also means discarding information that could potentially be relevant.

### Replacement of null data

One of the columns containing null values ​​is `"cliente.tempo_servico"` (*client.time_service*). Since we have `"conta.cobranca.Total"` (*account.charge.Total*) column, and we also have the `"conta.cobranca.mensal"` (*account.charge.monthly*) column, we can use the latter to calculate the duration (months) for which the client has been using the service.

In [89]:
filter = no_empty_data['cliente.tempo_servico'].isna()

In [90]:
no_empty_data[filter][['cliente.tempo_servico', 'conta.cobranca.mensal', 'conta.cobranca.Total']]

      cliente.tempo_servico  conta.cobranca.mensal  conta.cobranca.Total
9                       NaN                  90.45               5957.90
176                     NaN                  29.30                355.90
181                     NaN                  63.95                318.10
751                     NaN                 101.05               5971.25
3523                    NaN                  76.10               1054.80
5273                    NaN                  20.60                116.60
5276                    NaN                  73.85               3581.40
6134                    NaN                  69.05               1958.45

In [91]:
import numpy as np

np.ceil(5957.90 / 90.45)

np.float64(66.0)

In [92]:
no_empty_data['cliente.tempo_servico'].fillna(
    np.ceil(
        no_empty_data['conta.cobranca.Total'] / no_empty_data['conta.cobranca.mensal']
    ), inplace=True
)

/tmp/ipykernel_1253/1199128720.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  no_empty_data['cliente.tempo_servico'].fillna(

In [93]:
no_empty_data[filter][['cliente.tempo_servico', 'conta.cobranca.mensal', 'conta.cobranca.Total']]

      cliente.tempo_servico  conta.cobranca.mensal  conta.cobranca.Total
9                      66.0                  90.45               5957.90
176                    13.0                  29.30                355.90
181                     5.0                  63.95                318.10
751                    60.0                 101.05               5971.25
3523                   14.0                  76.10               1054.80
5273                    6.0                  20.60                116.60
5276                   49.0                  73.85               3581.40
6134                   29.0                  69.05               1958.45

In [94]:
no_empty_data.isna().sum()

id_cliente                        0
Churn                             0
cliente.genero                    0
cliente.idoso                     0
cliente.parceiro                  0
cliente.dependentes               0
cliente.tempo_servico             0
telefone.servico_telefone         0
telefone.varias_linhas            0
internet.servico_internet         0
internet.seguranca_online         0
internet.backup_online            0
internet.protecao_dispositivo     0
internet.suporte_tecnico          0
internet.tv_streaming             0
internet.filmes_streaming         0
conta.contrato                   31
conta.faturamente_eletronico     17
conta.metodo_pagamento           26
conta.cobranca.mensal            17
conta.cobranca.Total             15
dtype: int64

We now have the `conta.contrato` column, which contains null values ​​that need to be analyzed. Since we have not yet decided to drop any samples, we might consider filling these null values ​​with the most frequent value.

To do this, we need to examine the data within the column. Therefore, we use a Pandas method called `value_counts()`.

In [95]:
no_empty_data['conta.contrato'].value_counts()

conta.contrato
mes a mes    3861
dois anos    1688
um ano       1463
Name: count, dtype: int64

Upon conducting the analysis, we observed that the most frequent value is `month-to-month`; however, the difference in frequency compared to other values ​​is not particularly significant.

Therefore, we will not impute the missing values ​​using the most frequent value, as doing so would compromise the dataset for the following reasons:

- Data bias: The machine learning model would attempt to identify patterns that are, in fact, incorrect—since they do not reflect the actual data. This can lead to misleading, inaccurate, and unsatisfactory predictions.

- Distortion of results: Introducing an incorrect value causes the model to learn from flawed data, which, in turn, can result in inaccurate predictions.

***


Given that the columns `conta.cobranca_mensal` (*account.charge_monthly*) and `conta.cobranca.Total` (*account.charge.Total*) already have an established relationship—both with each other and with `cliente.tempo_servico` (*client.time_service*)—it may be possible to correctly infer data from them.

What remains is to make a decision regarding the columns `conta.contrato` (*account.contract*), `conta.faturamento_eletronico` (*account.electronic_billing*), and `conta.metodo_pagamento` (*account.payment_method*).

In [96]:
no_empty_data[['conta.contrato', 'conta.faturamente_eletronico' ,'conta.metodo_pagamento']]

     conta.contrato conta.faturamente_eletronico conta.metodo_pagamento
0              None                         None                   None
1         mes a mes                          nao    cheque pelo correio
2         mes a mes                          sim      cheque eletronico
3         mes a mes                          sim      cheque eletronico
4         mes a mes                          sim    cheque pelo correio
...             ...                          ...                    ...
7038         um ano                          nao    cheque pelo correio
7039      mes a mes                          sim      cheque eletronico
7040      mes a mes                          sim    cheque pelo correio
7041      dois anos                          nao    cheque pelo correio
7042      dois anos                          nao      cheque eletronico

[7043 rows x 3 columns]

### Removal of null data

After analyzing the columns containing null values, we determined that it is not possible to accurately infer these missing values ​​based on other data in our *dataframe*. Furthermore, their presence could compromise the efficiency of our machine learning model.

Therefore, we can choose to `drop / exclude` these samples.

In [97]:
columns_drop = ['conta.contrato', 'conta.faturamente_eletronico', 'conta.metodo_pagamento']

In [98]:
no_empty_data[columns_drop].isna().any(axis=1)

0        True
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Length: 7043, dtype: bool

In [99]:
no_empty_data[columns_drop].isna().any(axis=1).sum()

np.int64(37)

We discovered that there are 37 rows containing at least one null value across the three columns. So, we will use another Pandas method called `dropna()`.

In [100]:
no_empty_data.dropna(subset=columns_drop)

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
1,0003-MKNFE,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,...,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.90,542.40
2,0004-TLHLJ,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.90,280.85
3,0011-IGKFF,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.00,1237.85
4,0013-EXCHZ,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,...,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.90,267.40
5,0013-MHZWF,nao,feminino,0,nao,sim,9.0,sim,nao,DSL,...,nao,nao,sim,sim,sim,mes a mes,sim,cartao de credito (automatico),69.40,571.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,9987-LUTYD,nao,feminino,0,nao,nao,13.0,sim,nao,DSL,...,nao,nao,sim,nao,nao,um ano,nao,cheque pelo correio,55.15,742.90
7039,9992-RRAMN,sim,masculino,0,sim,nao,22.0,sim,sim,fibra otica,...,nao,nao,nao,nao,sim,mes a mes,sim,cheque eletronico,85.10,1873.70
7040,9992-UJOEL,nao,masculino,0,nao,nao,2.0,sim,nao,DSL,...,sim,nao,nao,nao,nao,mes a mes,sim,cheque pelo correio,50.30,92.75
7041,9993-LHIEB,nao,masculino,0,sim,sim,67.0,sim,nao,DSL,...,nao,sim,sim,nao,sim,dois anos,nao,cheque pelo correio,67.85,4627.65
7042,9995-HOTOH,nao,masculino,0,sim,sim,63.0,nao,sem servico de telefone,DSL,...,sim,sim,nao,sim,sim,dois anos,nao,cheque eletronico,59.00,3707.60

In [101]:
df_without_null = no_empty_data.dropna(subset=columns_drop).copy()
df_without_null.head()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
1,0003-MKNFE,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,...,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.9,542.40
2,0004-TLHLJ,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.9,280.85
3,0011-IGKFF,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.0,1237.85
4,0013-EXCHZ,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,...,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.9,267.40
5,0013-MHZWF,nao,feminino,0,nao,sim,9.0,sim,nao,DSL,...,nao,nao,sim,sim,sim,mes a mes,sim,cartao de credito (automatico),69.4,571.45

In [102]:
df_without_null.reset_index(drop=True, inplace=True)
df_without_null.head()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0003-MKNFE,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,...,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.9,542.40
1,0004-TLHLJ,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.9,280.85
2,0011-IGKFF,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.0,1237.85
3,0013-EXCHZ,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,...,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.9,267.40
4,0013-MHZWF,nao,feminino,0,nao,sim,9.0,sim,nao,DSL,...,nao,nao,sim,sim,sim,mes a mes,sim,cartao de credito (automatico),69.4,571.45

In [103]:
df_without_null.isna().sum()

id_cliente                       0
Churn                            0
cliente.genero                   0
cliente.idoso                    0
cliente.parceiro                 0
cliente.dependentes              0
cliente.tempo_servico            0
telefone.servico_telefone        0
telefone.varias_linhas           0
internet.servico_internet        0
internet.seguranca_online        0
internet.backup_online           0
internet.protecao_dispositivo    0
internet.suporte_tecnico         0
internet.tv_streaming            0
internet.filmes_streaming        0
conta.contrato                   0
conta.faturamente_eletronico     0
conta.metodo_pagamento           0
conta.cobranca.mensal            0
conta.cobranca.Total             0
dtype: int64

The output for our new *dataframe* shows that all columns have zero null values. This means there are no longer any null values ​​in our dataset.

***
**But what happened to the null values ​​that were in the 'conta.cobranca.mensal' and 'conta.cobranca.Total' columns?**
***

The values ​​that were null in these two columns were also null in the three columns we were working with. When we removed the samples containing null values ​​in those three columns, we also removed the samples that had null values ​​in `conta.cobranca.mensal` and `conta.cobranca.Total`. In other words, they were the same samples.

In [105]:
no_empty_data.to_json('telecon_normalized_data_v3.json')

In [106]:
df_without_null.to_json('subset_without_null.json')